export const onboardingSteps = [
  {
    title: 'Welcome to Zariya! 👋',
    description: 'We are excited to have you on board. Let’s take a brief 2-minute walkthrough to explain the core panels and how you can utilise them to manage budget, actuals, and reporting.',
    target: null,
    placement: 'center',
    route: '/dashboard',
  },
  {
    title: 'Navigation Rail',
    description: 'This sidebar is your main navigation rail. You can easily access the Dashboard, the Donors Registry, active Grant Agreements, and track individual Donations. Navigation is permissions-based to keep views clean.',
    target: '#tour-sidenav',
    placement: 'right',
    route: '/dashboard',
  },
  {
    title: 'Financial Health KPIs',
    description: 'These summary cards display live financial positions. "Funding committed" shows the outstanding pipeline (receivables yet to be received), and "Available" shows your unspent, active funds.',
    target: '#tour-kpis',
    placement: 'bottom',
    route: '/dashboard',
  },
  {
    title: 'The Funding Chain',
    description: 'The Funding Chain visualises the flow of money: starting from committed grants, moving to actual receipts (received), then to program allocations (utilised), showing the available balance.',
    target: '#tour-funding-chain',
    placement: 'bottom',
    route: '/dashboard',
  },
  {
    title: 'Recent Grant Agreements',
    description: 'A summary list of recently signed grant agreements. You can click on any row in the list to drill down into agreement details, schedules, and active disbursements.',
    target: '#tour-recent-grants',
    placement: 'top',
    route: '/dashboard',
  },
  {
    title: 'Donors Registry',
    description: 'Let’s check the Donors Registry page. Here you can search, filter, and view details for all mapped funding sources within the organisation.',
    target: '#tour-donors-filters',
    placement: 'bottom',
    route: '/donors',
  },
  {
    title: 'Registering New Donors',
    description: 'Need to add a new donor? Click the "New donor" button to open the registration form and add key details like type and fund source domicile.',
    target: '#tour-new-donor',
    placement: 'bottom',
    route: '/donors',
  },
  {
    title: 'Grant Agreements List',
    description: 'Next is the Grant Agreements page. Here you track all active, pending, or completed grant contracts, their schedules, and financial classifications.',
    target: '#tour-new-grant',
    placement: 'bottom',
    route: '/grants',
  },
  {
    title: 'Donations Ledger',
    description: 'Finally, the Donations Ledger tracks individual incoming cash or Gift-In-Kind receipts. Click "New donation" to record a new receipt.',
    target: '#tour-new-donation',
    placement: 'bottom',
    route: '/donations',
  },
  {
    title: 'Workspace Controls & Help',
    description: 'We are back on the Dashboard! Toggle light/dark themes, view notifications, or logout. Click the Help icon at any time to replay this tour.',
    target: '#tour-topbar',
    placement: 'bottom',
    route: '/dashboard',
  },
];
