-- V108: Split inflow-budget receipt detail out of donor_tranche_criterion into
--       its own inflow_receipt table — one row per instalment instead of
--       squashing multiple receipts into semicolon-joined bank_reference /
--       receipt_voucher_no strings on the criterion. Backfilled from the
--       CREDIT transactions that already posted a receipt.
CREATE TABLE inflow_receipt (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tranche_criterion_id  BIGINT NOT NULL REFERENCES donor_tranche_criterion(id) ON DELETE CASCADE,
    received_date         DATE NOT NULL,
    received_amount       NUMERIC(19, 2) NOT NULL,
    bank_reference        VARCHAR(100),
    receipt_voucher_no    VARCHAR(100),
    variance_reason       VARCHAR(500),
    transaction_id        BIGINT UNIQUE,
    created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by            VARCHAR(255),
    updated_by            VARCHAR(255)
);

CREATE INDEX idx_inflow_receipt_criterion ON inflow_receipt(tranche_criterion_id);

INSERT INTO inflow_receipt (tranche_criterion_id, received_date, received_amount, bank_reference, receipt_voucher_no, transaction_id)
SELECT ft.inflow_budget_line_id, ft.transaction_date, ft.amount, ft.reference, ft.transaction_code, ft.id
FROM finance_transaction ft
WHERE ft.type = 'CREDIT' AND ft.inflow_budget_line_id IS NOT NULL;

ALTER TABLE donor_tranche_criterion
    DROP COLUMN IF EXISTS actual_received_date,
    DROP COLUMN IF EXISTS actual_received_amount,
    DROP COLUMN IF EXISTS bank_reference,
    DROP COLUMN IF EXISTS receipt_voucher_no,
    DROP COLUMN IF EXISTS variance_reason;
