-- V109: Budget Category master — the heads a budget line is booked against
--       (Personnel, Travel, Admin & overheads, …), managed under Master
--       Configuration. `code` is the stable key budget lines store, so a
--       category can be renamed without breaking existing lines.
CREATE TABLE budget_category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(60)  NOT NULL UNIQUE,
    name        VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(500),
    status      BOOLEAN NOT NULL DEFAULT true,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255)
);

CREATE INDEX idx_budget_category_status ON budget_category(status);

-- Same six heads the frontend Budget module shipped with (codes must match).
INSERT INTO budget_category (code, name, description, status) VALUES
('PERSONNEL',   'Personnel',            'Salaries, stipends and staff benefits',       true),
('PROGRAMME',   'Programme activities', 'Direct activity and implementation costs',    true),
('CONSULTANTS', 'Consultants',          'Studies, audits and professional services',   true),
('TRAVEL',      'Travel',               'Field visits, conveyance and lodging',        true),
('EQUIPMENT',   'Equipment & assets',   'Capital purchases and equipment',             true),
('ADMIN',       'Admin & overheads',    'Rent, utilities and shared office costs',     true);
