-- V111: Budget module — a budget per programme (or for the organisation as a
--       whole) and financial year, its quarterly-phased lines, and the
--       approval history (Draft → Submitted → Approved | Rejected).

CREATE TABLE budget (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_code     VARCHAR(30)  NOT NULL UNIQUE,       -- BUD-2026-001
    name            VARCHAR(255) NOT NULL,
    financial_year  VARCHAR(7)   NOT NULL,              -- "2026-27" (Apr–Mar)
    budget_type     VARCHAR(20)  NOT NULL,              -- PROGRAMME | ORGANISATION
    programme_id    BIGINT REFERENCES programme(id),    -- required for PROGRAMME budgets
    state_id        BIGINT REFERENCES state_master(id), -- null = all states
    owner           VARCHAR(255),
    notes           VARCHAR(1000),
    status          VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    CONSTRAINT ck_budget_type   CHECK (budget_type IN ('PROGRAMME', 'ORGANISATION')),
    CONSTRAINT ck_budget_status CHECK (status IN ('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED')),
    CONSTRAINT ck_budget_programme CHECK (budget_type <> 'PROGRAMME' OR programme_id IS NOT NULL)
);

CREATE INDEX idx_budget_financial_year ON budget(financial_year);
CREATE INDEX idx_budget_status ON budget(status);

CREATE TABLE budget_line (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_id    BIGINT NOT NULL REFERENCES budget(id) ON DELETE CASCADE,
    line_no      INT    NOT NULL,                        -- 1, 2, 3… shown as BL-01
    category_id  BIGINT NOT NULL REFERENCES budget_category(id),
    description  VARCHAR(500) NOT NULL,
    book         VARCHAR(2)   NOT NULL,                  -- LC | FC
    q1           NUMERIC(18, 2) NOT NULL DEFAULT 0,      -- Apr–Jun
    q2           NUMERIC(18, 2) NOT NULL DEFAULT 0,      -- Jul–Sep
    q3           NUMERIC(18, 2) NOT NULL DEFAULT 0,      -- Oct–Dec
    q4           NUMERIC(18, 2) NOT NULL DEFAULT 0,      -- Jan–Mar
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by   VARCHAR(255),
    updated_by   VARCHAR(255),
    CONSTRAINT uq_budget_line_no UNIQUE (budget_id, line_no),
    CONSTRAINT ck_budget_line_book CHECK (book IN ('LC', 'FC')),
    CONSTRAINT ck_budget_line_amounts CHECK (q1 >= 0 AND q2 >= 0 AND q3 >= 0 AND q4 >= 0)
);

CREATE INDEX idx_budget_line_category ON budget_line(category_id);

CREATE TABLE budget_status_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    budget_id   BIGINT NOT NULL REFERENCES budget(id) ON DELETE CASCADE,
    status      VARCHAR(20) NOT NULL,
    note        VARCHAR(1000),
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,  -- when the change happened
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  VARCHAR(255),                                 -- who made it
    updated_by  VARCHAR(255)
);

CREATE INDEX idx_budget_status_history_budget ON budget_status_history(budget_id);
