-- V114: Debit and credit notes against the outflow schedule.
--
-- The outflow schedule itself is not stored: it is derived from APPROVED
-- budgets — one row per budget line per quarter with an amount. A note points
-- at such a row by (budget_line_id, quarter).
--
-- Master-data picks (payee, payment mode, bank account, group, ledger, donor,
-- fund profile, grant, tranche) are stored as id + name snapshots, so a note
-- still reads correctly if the master record is later renamed or removed.
-- Ids are VARCHAR because not every source uses numeric ids (e.g. payees).

CREATE TABLE debit_note (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_code           VARCHAR(30)    NOT NULL UNIQUE,          -- DN-2026-001
    budget_line_id      BIGINT         NOT NULL REFERENCES budget_line(id),
    quarter             SMALLINT       NOT NULL,                 -- 1..4
    note_date           DATE           NOT NULL,
    amount              NUMERIC(18, 2) NOT NULL,
    reason              VARCHAR(40),                             -- only when the note takes the row over budget
    book                VARCHAR(2)     NOT NULL,                 -- LC | FC
    payee_category      VARCHAR(20)    NOT NULL,
    payee_ref           VARCHAR(64),
    payee_name          VARCHAR(255)   NOT NULL,
    payment_mode_ref    VARCHAR(64),
    payment_mode_name   VARCHAR(255)   NOT NULL,
    bank_account_ref    VARCHAR(64),
    bank_account_name   VARCHAR(255),
    group_ref           VARCHAR(64),
    group_name          VARCHAR(255)   NOT NULL,
    ledger_ref          VARCHAR(64),
    ledger_name         VARCHAR(255),
    donor_ref           VARCHAR(64),
    donor_name          VARCHAR(255),
    fund_profile_ref    VARCHAR(64),
    fund_profile_name   VARCHAR(255),
    grant_ref           VARCHAR(64),
    grant_name          VARCHAR(255),
    reference           VARCHAR(255),
    remarks             VARCHAR(1000),
    attachment_name     VARCHAR(255),                            -- file name only; no file storage yet
    status              VARCHAR(20)    NOT NULL DEFAULT 'ISSUED',
    cancelled_by        VARCHAR(255),
    cancelled_at        TIMESTAMP,
    cancel_note         VARCHAR(1000),
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    CONSTRAINT ck_debit_note_quarter CHECK (quarter BETWEEN 1 AND 4),
    CONSTRAINT ck_debit_note_amount  CHECK (amount > 0),
    CONSTRAINT ck_debit_note_book    CHECK (book IN ('LC', 'FC')),
    CONSTRAINT ck_debit_note_status  CHECK (status IN ('ISSUED', 'CANCELLED')),
    CONSTRAINT ck_debit_note_fund    CHECK (fund_profile_name IS NULL OR donor_name IS NOT NULL)
);

CREATE INDEX idx_debit_note_line ON debit_note(budget_line_id, quarter);
CREATE INDEX idx_debit_note_status ON debit_note(status);

CREATE TABLE credit_note (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_code           VARCHAR(30)    NOT NULL UNIQUE,          -- CN-2026-001
    budget_line_id      BIGINT REFERENCES budget_line(id),       -- optional: credited against an outflow row
    quarter             SMALLINT,
    debit_note_id       BIGINT REFERENCES debit_note(id),        -- optional: reverses (part of) this debit note
    note_date           DATE           NOT NULL,
    amount              NUMERIC(18, 2) NOT NULL,
    reason              VARCHAR(40),
    book                VARCHAR(2)     NOT NULL,
    payee_category      VARCHAR(20),
    payee_ref           VARCHAR(64),
    payee_name          VARCHAR(255),
    payment_mode_ref    VARCHAR(64),
    payment_mode_name   VARCHAR(255)   NOT NULL,
    bank_account_ref    VARCHAR(64),
    bank_account_name   VARCHAR(255),
    group_ref           VARCHAR(64),
    group_name          VARCHAR(255),
    ledger_ref          VARCHAR(64),
    ledger_name         VARCHAR(255),
    donor_ref           VARCHAR(64),
    donor_name          VARCHAR(255),
    fund_profile_ref    VARCHAR(64),
    fund_profile_name   VARCHAR(255),
    grant_ref           VARCHAR(64),
    grant_name          VARCHAR(255),
    disbursement_type   VARCHAR(40),                             -- snapshot of the fund profile's rule
    tranche_ref         VARCHAR(64),
    tranche_name        VARCHAR(255),
    reference           VARCHAR(255),
    remarks             VARCHAR(1000),
    attachment_name     VARCHAR(255),
    status              VARCHAR(20)    NOT NULL DEFAULT 'ISSUED',
    cancelled_by        VARCHAR(255),
    cancelled_at        TIMESTAMP,
    cancel_note         VARCHAR(1000),
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    CONSTRAINT ck_credit_note_quarter CHECK (quarter IS NULL OR quarter BETWEEN 1 AND 4),
    CONSTRAINT ck_credit_note_row     CHECK ((budget_line_id IS NULL) = (quarter IS NULL)),
    CONSTRAINT ck_credit_note_debit   CHECK (debit_note_id IS NULL OR budget_line_id IS NOT NULL),
    CONSTRAINT ck_credit_note_amount  CHECK (amount > 0),
    CONSTRAINT ck_credit_note_book    CHECK (book IN ('LC', 'FC')),
    CONSTRAINT ck_credit_note_status  CHECK (status IN ('ISSUED', 'CANCELLED')),
    CONSTRAINT ck_credit_note_fund    CHECK (fund_profile_name IS NULL OR donor_name IS NOT NULL)
);

CREATE INDEX idx_credit_note_line ON credit_note(budget_line_id, quarter);
CREATE INDEX idx_credit_note_debit ON credit_note(debit_note_id);
CREATE INDEX idx_credit_note_status ON credit_note(status);
