-- V14: Donor Fund Profile — the "behavioural heart" of the donor module
--      (workbook sheet 03). One donor has one or more fund profiles; a grant
--      inherits exactly one profile. The profile carries the fund-use rules
--      (mode, class, movement / explanation, overhead cap, reporting cadence).
--
-- IMPORTANT: `fund_class_code` (A/B/C) is the workbook's *restriction* class and
-- is DISTINCT from donor_master.fund_class (the DOMESTIC/CORPORATE/… typology
-- enum). They model different things and must not be conflated.
--   A = Fully restricted        (movement blocked, UC required)
--   B = Unrestricted w/ explan.  (movement allowed, audit entry per move)
--   C = Fully unrestricted       (movement allowed, aggregate reporting)
--   NULL = edge / pending        (programme-tied or unconfirmed at onboarding)

CREATE TABLE donor_fund_profile (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_id                BIGINT NOT NULL,
    fund_mode               VARCHAR(30),               -- 'Restricted' | 'Unrestricted'
    fund_class_code         CHAR(1),                   -- 'A' | 'B' | 'C' | NULL (edge/pending)
    purpose                 VARCHAR(255),
    programme_tied          BOOLEAN DEFAULT FALSE,
    programme_id            BIGINT,                    -- nullable: blank = untied/not-yet-tagged
    reporting_frequency     VARCHAR(30),               -- 'Quarterly' | 'Half-yearly' | 'Annual'
    admin_allowed           BOOLEAN DEFAULT TRUE,
    overhead_limit_percent  DECIMAL(5, 2),
    movement_allowed        BOOLEAN DEFAULT FALSE,
    explanation_required    BOOLEAN DEFAULT FALSE,
    onboarding_complete     BOOLEAN DEFAULT FALSE,
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by              VARCHAR(255),
    updated_by              VARCHAR(255),
    CONSTRAINT fk_profile_donor     FOREIGN KEY (donor_id)     REFERENCES donor_master(id) ON DELETE CASCADE,
    CONSTRAINT fk_profile_programme FOREIGN KEY (programme_id) REFERENCES programme(id),
    CONSTRAINT chk_fund_class_code  CHECK (fund_class_code IS NULL OR fund_class_code IN ('A', 'B', 'C'))
);

CREATE INDEX idx_profile_donor_id  ON donor_fund_profile(donor_id);
CREATE INDEX idx_profile_programme ON donor_fund_profile(programme_id);
CREATE INDEX idx_profile_class     ON donor_fund_profile(fund_class_code);
