-- V15: Fund-profile subtree — geography, utilisation rule, disbursement rule
--      (workbook sheets 04, 05, 06). In the workbook these hang off the DONOR
--      FUND PROFILE (donor-permitted scope & rules), NOT off the grant.
--
-- Design note: the existing grant_geography / grant_rule tables (V5) model
-- per-grant *delivery* geography and rules. These new tables model the
-- donor-permitted scope defined once per fund profile and inherited by every
-- grant on that profile. They are complementary, not replacements — see the
-- note handed back to the user for the reconciliation recommendation.

-- Geographies a fund profile may be spent in (one-to-many on fund profile).
CREATE TABLE donor_geography (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fund_profile_id BIGINT NOT NULL,
    geography_name  VARCHAR(255) NOT NULL,     -- free-form: 'Delhi NCR', 'Pan-India (untied)', …
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    CONSTRAINT fk_geo_profile FOREIGN KEY (fund_profile_id) REFERENCES donor_fund_profile(id) ON DELETE CASCADE
);

-- Quantitative caps per fund profile (overhead %, fundraising exclusion, …).
CREATE TABLE donor_utilisation_rule (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fund_profile_id  BIGINT NOT NULL,
    rule_type        VARCHAR(50) NOT NULL,     -- 'Admin / Overhead cap' | 'Fundraising cost exclusion' | …
    limit_percentage DECIMAL(5, 2),
    description      TEXT,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(255),
    updated_by       VARCHAR(255),
    CONSTRAINT fk_util_profile FOREIGN KEY (fund_profile_id) REFERENCES donor_fund_profile(id) ON DELETE CASCADE
);

-- How money is released per fund profile (tranche-on-UC / on-report / lump-sum / hold).
CREATE TABLE donor_disbursement_rule (
    id                            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fund_profile_id               BIGINT NOT NULL,
    rule_type                     VARCHAR(50) NOT NULL,   -- 'Tranche-on-UC' | 'Tranche-on-report' | 'Lump-sum / on-receipt' | 'Hold'
    release_trigger               VARCHAR(60),            -- 'Milestone + utilisation gate' | 'utilisation threshold' | 'Unconditional'
    min_prior_utilisation_required DECIMAL(5, 2),         -- e.g. 75.00 = release next tranche after 75% of prior utilised
    milestone_required            BOOLEAN DEFAULT FALSE,
    rule_description              TEXT,
    created_at                    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by                    VARCHAR(255),
    updated_by                    VARCHAR(255),
    CONSTRAINT fk_disb_profile FOREIGN KEY (fund_profile_id) REFERENCES donor_fund_profile(id) ON DELETE CASCADE
);

CREATE INDEX idx_geo_profile_id  ON donor_geography(fund_profile_id);
CREATE INDEX idx_util_profile_id ON donor_utilisation_rule(fund_profile_id);
CREATE INDEX idx_disb_profile_id ON donor_disbursement_rule(fund_profile_id);
