-- V25: Singleton org-level tax registration facts the donation tax chain
-- (80G eligibility, Form 10BD, Form 10BE) evaluates against. Seeded with a
-- placeholder registration so the chain has something to evaluate out of
-- the box; idempotent so this migration is safe to re-run.
CREATE TABLE tenant_tax_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_80g_registration_number VARCHAR(50) NOT NULL,
    org_80g_valid_from DATE NOT NULL,
    org_80g_valid_to DATE NOT NULL,
    section_35_registration_number VARCHAR(50),
    section_35_valid_from DATE,
    section_35_valid_to DATE,
    receipt_number_sequence BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM tenant_tax_config) THEN
        INSERT INTO tenant_tax_config (
            org_80g_registration_number, org_80g_valid_from, org_80g_valid_to,
            section_35_registration_number, section_35_valid_from, section_35_valid_to,
            receipt_number_sequence
        ) VALUES (
            'AAAAA0000A20240001', DATE '2024-04-01', DATE '2029-03-31',
            NULL, NULL, NULL,
            0
        );
    END IF;
END $$;
