-- V23: Country Master table + link state_master to country_master
CREATE TABLE country_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_code VARCHAR(10) NOT NULL UNIQUE,
    country_name VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

CREATE INDEX idx_country_code ON country_master(country_code);
CREATE INDEX idx_country_active ON country_master(is_active);

INSERT INTO country_master (country_code, country_name) VALUES ('IN', 'India');

ALTER TABLE state_master ADD COLUMN country_id BIGINT;

UPDATE state_master SET country_id = (SELECT id FROM country_master WHERE country_code = 'IN')
WHERE country_id IS NULL;

ALTER TABLE state_master ALTER COLUMN country_id SET NOT NULL;
ALTER TABLE state_master ADD CONSTRAINT fk_state_country FOREIGN KEY (country_id) REFERENCES country_master(id);

CREATE INDEX idx_state_country_id ON state_master(country_id);
