-- V2: Geography Master Tables + Programme
-- Create state master table
CREATE TABLE state_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_code VARCHAR(10) NOT NULL UNIQUE,
    state_name VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

-- Create district master table
CREATE TABLE district_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_id BIGINT NOT NULL,
    district_code VARCHAR(10) NOT NULL,
    district_name VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_district_state FOREIGN KEY (state_id) REFERENCES state_master(id)
);

-- Create city master table
CREATE TABLE city_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    district_id BIGINT NOT NULL,
    city_code VARCHAR(10) NOT NULL,
    city_name VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_city_district FOREIGN KEY (district_id) REFERENCES district_master(id)
);

-- Create programme master table
CREATE TABLE programme (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    programme_code VARCHAR(20) NOT NULL UNIQUE,
    programme_name VARCHAR(255) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

-- Create reporting schedule master table
CREATE TABLE reporting_schedule_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_name VARCHAR(255) NOT NULL,
    schedule_frequency VARCHAR(50) NOT NULL,
    description TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

-- Create indexes for geography tables
CREATE INDEX idx_state_code ON state_master(state_code);
CREATE INDEX idx_state_active ON state_master(is_active);
CREATE INDEX idx_district_state_id ON district_master(state_id);
CREATE INDEX idx_district_code ON district_master(district_code);
CREATE INDEX idx_city_district_id ON city_master(district_id);
CREATE INDEX idx_city_code ON city_master(city_code);
CREATE INDEX idx_programme_code ON programme(programme_code);
CREATE INDEX idx_programme_active ON programme(is_active);
