-- V38: Donation core — a gift received. Unlike grant_agreement (pledged,
-- released in tranches), a donation is income the moment it lands: there is
-- no committed stage, and donor_id is nullable because an anonymous
-- donation is never linked to a placeholder donor record.
CREATE TABLE donation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donation_code VARCHAR(30) NOT NULL UNIQUE,
    donation_type VARCHAR(30) NOT NULL,
    receipt_date DATE NOT NULL,
    channel VARCHAR(30) NOT NULL,
    book VARCHAR(5) NOT NULL,

    donor_id BIGINT,
    identification VARCHAR(20) NOT NULL,
    anonymous_collection_source VARCHAR(100),
    anonymous_source_reference VARCHAR(500),

    fund_mode VARCHAR(20) NOT NULL,
    fund_class_code VARCHAR(1),
    programme_id BIGINT,
    utilisation_period_type VARCHAR(20) NOT NULL,
    utilisation_start_date DATE,
    utilisation_end_date DATE,
    is_conditional_gift BOOLEAN NOT NULL DEFAULT FALSE,
    condition_description TEXT,

    currency VARCHAR(10) NOT NULL DEFAULT 'INR',
    amount DECIMAL(18, 2) NOT NULL,
    fx_rate DECIMAL(12, 4) NOT NULL DEFAULT 1,
    reporting_amount_inr DECIMAL(18, 2),
    bank_account_type VARCHAR(30) NOT NULL,
    transaction_ref VARCHAR(100),
    tally_voucher_ref VARCHAR(100),

    recognition_status VARCHAR(20) NOT NULL,

    eighty_g_status VARCHAR(40) NOT NULL,
    eighty_g_receipt_number VARCHAR(30),
    eighty_g_issued_at TIMESTAMP,
    ten_bd_reportable BOOLEAN NOT NULL,
    ten_bd_failure_reason VARCHAR(255),
    ten_be_status VARCHAR(30) NOT NULL,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),

    CONSTRAINT fk_donation_donor FOREIGN KEY (donor_id) REFERENCES donor_master(id),
    CONSTRAINT fk_donation_programme FOREIGN KEY (programme_id) REFERENCES programme(id)
);

CREATE INDEX idx_donation_code ON donation(donation_code);
CREATE INDEX idx_donation_donor_id ON donation(donor_id);
CREATE INDEX idx_donation_type ON donation(donation_type);
CREATE INDEX idx_donation_book ON donation(book);
CREATE INDEX idx_donation_receipt_date ON donation(receipt_date);
CREATE INDEX idx_donation_eighty_g_status ON donation(eighty_g_status);
CREATE INDEX idx_donation_ten_bd_reportable ON donation(ten_bd_reportable);
CREATE INDEX idx_donation_identification ON donation(identification);

-- Multi-select state list a donation's use is tied to; feeds FCRA state-wise
-- disclosure. Mirrors grant_geography.
CREATE TABLE donation_location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donation_id BIGINT NOT NULL,
    state_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_donation_location_donation FOREIGN KEY (donation_id) REFERENCES donation(id) ON DELETE CASCADE,
    CONSTRAINT fk_donation_location_state FOREIGN KEY (state_id) REFERENCES state_master(id)
);

CREATE INDEX idx_donation_location_donation_id ON donation_location(donation_id);
