-- V39: Type-specific detail blocks. Only the block matching a donation's
-- donation_type is ever populated for that row.

-- Gift-in-kind line items — one gift may contain several items, each with
-- its own intended use driving the accounting leg.
CREATE TABLE donation_gik_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donation_id BIGINT NOT NULL,
    item_description VARCHAR(255) NOT NULL,
    fair_value DECIMAL(18, 2) NOT NULL,
    intended_use VARCHAR(20) NOT NULL,
    expiry_date DATE,
    liquidation_due_date DATE,
    realisation_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_gik_item_donation FOREIGN KEY (donation_id) REFERENCES donation(id) ON DELETE CASCADE
);

CREATE INDEX idx_gik_item_donation_id ON donation_gik_item(donation_id);

-- Logged history of intended-use changes — "received to distribute, then
-- sold near expiry" is recorded, never silently overwritten.
CREATE TABLE donation_gik_intended_use_change (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gik_item_id BIGINT NOT NULL,
    from_intended_use VARCHAR(20) NOT NULL,
    to_intended_use VARCHAR(20) NOT NULL,
    reason TEXT NOT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_gik_use_change_item FOREIGN KEY (gik_item_id) REFERENCES donation_gik_item(id) ON DELETE CASCADE
);

CREATE INDEX idx_gik_use_change_item_id ON donation_gik_intended_use_change(gik_item_id);

-- Corpus — written donor direction is mandatory; principal is capital, never income.
CREATE TABLE donation_corpus_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donation_id BIGINT NOT NULL UNIQUE,
    written_direction_ref VARCHAR(255) NOT NULL,
    direction_date DATE NOT NULL,
    direction_document_path VARCHAR(500) NOT NULL,
    investment_mode VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_corpus_detail_donation FOREIGN KEY (donation_id) REFERENCES donation(id) ON DELETE CASCADE
);

-- Recurring giving — a mandate, not a tranche. No release criteria.
CREATE TABLE donation_recurring_mandate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donation_id BIGINT NOT NULL UNIQUE,
    mandate_id VARCHAR(100) NOT NULL,
    frequency VARCHAR(20) NOT NULL,
    start_date DATE NOT NULL,
    mandate_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    next_expected_debit_date DATE,
    sponsorship_tie VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_recurring_mandate_donation FOREIGN KEY (donation_id) REFERENCES donation(id) ON DELETE CASCADE
);

-- Payroll giving — one employer remittance explodes into many employee rows.
CREATE TABLE donation_payroll_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donation_id BIGINT NOT NULL UNIQUE,
    employer VARCHAR(255) NOT NULL,
    employer_match_routing VARCHAR(30) NOT NULL DEFAULT 'PAYROLL_GIVING_TAGGED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_payroll_batch_donation FOREIGN KEY (donation_id) REFERENCES donation(id) ON DELETE CASCADE
);

CREATE TABLE donation_payroll_employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    id_type VARCHAR(30),
    id_number VARCHAR(50),
    amount DECIMAL(15, 2) NOT NULL,
    citizenship VARCHAR(10) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_payroll_employee_batch FOREIGN KEY (batch_id) REFERENCES donation_payroll_batch(id) ON DELETE CASCADE
);

CREATE INDEX idx_payroll_employee_batch_id ON donation_payroll_employee(batch_id);

-- Legacy / bequest — not income until probate clears.
CREATE TABLE donation_legacy_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donation_id BIGINT NOT NULL UNIQUE,
    bequest_status VARCHAR(20) NOT NULL,
    probate_reference VARCHAR(255),
    expected_value DECIMAL(18, 2),
    estate_domicile VARCHAR(10) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_legacy_detail_donation FOREIGN KEY (donation_id) REFERENCES donation(id) ON DELETE CASCADE
);
