-- V3: Donor Master + Donor Contact
CREATE TABLE donor_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_code VARCHAR(20) NOT NULL UNIQUE,
    donor_name VARCHAR(255) NOT NULL,
    donor_type VARCHAR(50) NOT NULL,
    fund_class VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    website VARCHAR(255),
    registration_number VARCHAR(100),
    tax_id VARCHAR(100),
    address TEXT,
    city_id BIGINT,
    state_id BIGINT,
    country VARCHAR(100) DEFAULT 'India',
    postal_code VARCHAR(20),
    status VARCHAR(50) DEFAULT 'DRAFT',
    onboarding_step INT DEFAULT 1,
    is_active BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_donor_city FOREIGN KEY (city_id) REFERENCES city_master(id),
    CONSTRAINT fk_donor_state FOREIGN KEY (state_id) REFERENCES state_master(id)
);

-- Create donor contact table
CREATE TABLE donor_contact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_id BIGINT NOT NULL,
    contact_name VARCHAR(255) NOT NULL,
    contact_title VARCHAR(100),
    email VARCHAR(255),
    phone_number VARCHAR(20),
    mobile_number VARCHAR(20),
    address TEXT,
    city_id BIGINT,
    state_id BIGINT,
    postal_code VARCHAR(20),
    contact_type VARCHAR(50),
    is_primary BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_contact_donor FOREIGN KEY (donor_id) REFERENCES donor_master(id) ON DELETE CASCADE,
    CONSTRAINT fk_contact_city FOREIGN KEY (city_id) REFERENCES city_master(id),
    CONSTRAINT fk_contact_state FOREIGN KEY (state_id) REFERENCES state_master(id)
);

-- Create donor mapping table
CREATE TABLE donor_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_id BIGINT NOT NULL UNIQUE,
    external_donor_id VARCHAR(100),
    mapping_metadata TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_mapping_donor FOREIGN KEY (donor_id) REFERENCES donor_master(id) ON DELETE CASCADE
);

-- Create indexes for donor tables
CREATE INDEX idx_donor_code ON donor_master(donor_code);
CREATE INDEX idx_donor_status ON donor_master(status);
CREATE INDEX idx_donor_active ON donor_master(is_active);
CREATE INDEX idx_donor_email ON donor_master(email);
CREATE INDEX idx_contact_donor_id ON donor_contact(donor_id);
CREATE INDEX idx_contact_email ON donor_contact(email);
CREATE INDEX idx_mapping_donor_id ON donor_mapping(donor_id);
