-- V41: Fund-profile tranche plan — the committed release schedule agreed with the
--      donor for a fund profile, held once per profile and inherited by every
--      grant on it. A grant agreement's Total Grant Amount is the SUM of these
--      rows (New Grant Agreement Form, section 2), so the grant form no longer
--      takes an entered total.
--
-- Distinct from grant_tranche (V5): that table tracks the *actual* per-grant
-- release/utilisation lifecycle. This one is the donor-side plan.

CREATE TABLE fund_profile_tranche (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fund_profile_id     BIGINT NOT NULL,
    tranche_number      INTEGER NOT NULL,
    tranche_name        VARCHAR(255),
    tranche_amount      DECIMAL(15, 2) NOT NULL,
    planned_release_date DATE,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    CONSTRAINT fk_profile_tranche_profile FOREIGN KEY (fund_profile_id)
        REFERENCES donor_fund_profile(id) ON DELETE CASCADE,
    CONSTRAINT chk_profile_tranche_amount CHECK (tranche_amount > 0),
    -- DEFERRED because editing a profile replaces its whole schedule: Hibernate
    -- issues the new inserts before the orphan deletes, which trips an immediate
    -- unique check on (profile, number) even though the committed state is valid.
    CONSTRAINT uq_profile_tranche_number UNIQUE (fund_profile_id, tranche_number)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX idx_profile_tranche_profile_id ON fund_profile_tranche(fund_profile_id);

-- Seed each existing profile with a single tranche carrying the total already
-- entered on its grants, so grants keep their current Total Grant Amount once it
-- becomes profile-derived. Profiles with no grants get no tranche (planned total
-- 0 until someone fills the schedule in).
INSERT INTO fund_profile_tranche (fund_profile_id, tranche_number, tranche_name, tranche_amount)
SELECT g.fund_profile_id, 1, 'Migrated from grant total', MAX(g.total_grant_amount)
FROM grant_agreement g
WHERE g.fund_profile_id IS NOT NULL
  AND g.total_grant_amount > 0
GROUP BY g.fund_profile_id;
