-- V42: FX reference rates → INR. Backs the "FX Rate → INR (at signing, locked)"
--      field on the New Grant Agreement Form, which auto-fills from the RBI rate
--      for the agreement date and stays editable.
--
-- Rows are cached lookups, not accounting records: a grant locks its own rate in
-- grant_agreement.fx_locked_rate at signing, so later corrections here never
-- move an existing grant's reporting amount.

CREATE TABLE fx_rate (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    currency    VARCHAR(10) NOT NULL,
    rate_date   DATE NOT NULL,
    rate_to_inr DECIMAL(12, 4) NOT NULL,
    source      VARCHAR(50) NOT NULL,          -- 'RBI' | 'SEED' | 'MANUAL'
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    CONSTRAINT chk_fx_rate_positive CHECK (rate_to_inr > 0),
    CONSTRAINT uq_fx_rate_currency_date UNIQUE (currency, rate_date)
);

CREATE INDEX idx_fx_rate_currency_date ON fx_rate(currency, rate_date DESC);

-- Placeholder baseline so the grant form auto-fills before an RBI feed is wired
-- up (zaria.fx.rbi.enabled). Source is marked SEED, not RBI, precisely because
-- these are indicative dev values — point the provider at the real feed for
-- rates you can sign against.
INSERT INTO fx_rate (currency, rate_date, rate_to_inr, source) VALUES
    ('USD', DATE '2026-01-01', 85.0000, 'SEED'),
    ('EUR', DATE '2026-01-01', 92.0000, 'SEED'),
    ('GBP', DATE '2026-01-01', 108.0000, 'SEED'),
    ('AUD', DATE '2026-01-01', 56.0000, 'SEED'),
    ('CAD', DATE '2026-01-01', 61.0000, 'SEED'),
    ('CHF', DATE '2026-01-01', 96.0000, 'SEED'),
    ('JPY', DATE '2026-01-01', 0.5600, 'SEED'),
    ('SGD', DATE '2026-01-01', 63.0000, 'SEED');
