-- V44: Grant disbursement schedule — how an agreement's funds are released
--      (Disbursement Rules spec §1). One schedule per grant.
--
-- Lump Sum is modelled as a one-tranche schedule rather than a separate shape:
-- the single receiving date is kept here, and the service maintains exactly one
-- grant_tranche row for it. Receipts, utilisation certificates and the dashboard
-- funding chain therefore need no special-casing for lump-sum grants.
--
-- The committed total is NOT stored: it is the grant's total_grant_amount
-- (itself Σ of the fund profile's tranche plan). Storing it again would create a
-- third number that could contradict the finalisation rule below.

CREATE TABLE grant_disbursement_schedule (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grant_id          BIGINT NOT NULL UNIQUE,
    disbursement_type VARCHAR(20) NOT NULL,       -- 'LUMP_SUM' | 'TRANCHES'
    receiving_date    DATE,                       -- lump sum only
    schedule_type     VARCHAR(20),                -- tranches only: MONTHLY | QUARTERLY | HALF_YEARLY | YEARLY
    finalised         BOOLEAN NOT NULL DEFAULT FALSE,
    finalised_at      TIMESTAMP,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by        VARCHAR(255),
    updated_by        VARCHAR(255),
    CONSTRAINT fk_disbursement_grant FOREIGN KEY (grant_id)
        REFERENCES grant_agreement(id) ON DELETE CASCADE,
    CONSTRAINT chk_disbursement_type CHECK (disbursement_type IN ('LUMP_SUM', 'TRANCHES')),
    CONSTRAINT chk_schedule_type CHECK (
        schedule_type IS NULL OR schedule_type IN ('MONTHLY', 'QUARTERLY', 'HALF_YEARLY', 'YEARLY')),
    -- Each type carries only its own field: a lump sum has a receiving date and
    -- no cadence; tranches have a cadence and no single receiving date.
    CONSTRAINT chk_disbursement_shape CHECK (
        (disbursement_type = 'LUMP_SUM' AND schedule_type IS NULL)
        OR (disbursement_type = 'TRANCHES' AND receiving_date IS NULL))
);

CREATE INDEX idx_disbursement_grant_id ON grant_disbursement_schedule(grant_id);
