-- V45: Structured release criteria per tranche (Disbursement Rules §4).
--      A tranche may carry several; each release gate is now a row with typed
--      fields instead of the free text in grant_tranche.conditions_to_release.
--
-- One sparse table with per-type CHECK constraints rather than ten tables: the
-- shapes are small, always read together, and the DB still refuses a milestone
-- criterion with no milestone name.
--
-- grant_tranche.conditions_to_release and prior_utilisation_required are kept but
-- superseded — they are back-filled into criteria rows below and are no longer
-- written by the application.

CREATE TABLE grant_tranche_criteria (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tranche_id          BIGINT NOT NULL,
    sequence            INTEGER NOT NULL,
    criterion_type      VARCHAR(30) NOT NULL,
    -- Fixed Date
    release_date        DATE,
    -- Milestone Based
    milestone_name      VARCHAR(255),
    verification_role   VARCHAR(30),
    target_date         DATE,
    -- Utilisation Threshold
    utilisation_percent DECIMAL(5, 2),
    trigger_basis       VARCHAR(20),
    -- Utilisation Threshold (optional) / Other (mandatory)
    description         TEXT,
    -- Satisfaction track: the tranche's gate is open when every criterion is met.
    met                 BOOLEAN NOT NULL DEFAULT FALSE,
    met_at              TIMESTAMP,
    met_by              BIGINT,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    CONSTRAINT fk_criteria_tranche FOREIGN KEY (tranche_id)
        REFERENCES grant_tranche(id) ON DELETE CASCADE,
    CONSTRAINT fk_criteria_met_by FOREIGN KEY (met_by) REFERENCES users(id),
    CONSTRAINT chk_criterion_type CHECK (criterion_type IN (
        'ON_SIGNING', 'FIXED_DATE', 'MILESTONE_BASED', 'UTILISATION_THRESHOLD',
        'UTILISATION_CERTIFICATE', 'FINANCIAL_REPORT', 'NARRATIVE_REPORT',
        'AUDIT_REPORT', 'DONOR_APPROVAL', 'OTHER')),
    CONSTRAINT chk_criterion_verification_role CHECK (
        verification_role IS NULL OR verification_role IN (
            'PROGRAMME_MANAGER', 'CFO', 'HEAD_OF_ORGANISATION')),
    CONSTRAINT chk_criterion_trigger_basis CHECK (
        trigger_basis IS NULL OR trigger_basis IN ('PREVIOUS_TRANCHE', 'CUMULATIVE')),
    CONSTRAINT chk_criterion_utilisation_percent CHECK (
        utilisation_percent IS NULL OR (utilisation_percent > 0 AND utilisation_percent <= 100)),
    -- Mandatory fields per type, mirroring the spec's "Additional Fields".
    CONSTRAINT chk_criterion_fixed_date CHECK (
        criterion_type <> 'FIXED_DATE' OR release_date IS NOT NULL),
    CONSTRAINT chk_criterion_milestone CHECK (
        criterion_type <> 'MILESTONE_BASED'
        OR (milestone_name IS NOT NULL AND verification_role IS NOT NULL)),
    CONSTRAINT chk_criterion_threshold CHECK (
        criterion_type <> 'UTILISATION_THRESHOLD'
        OR (utilisation_percent IS NOT NULL AND trigger_basis IS NOT NULL)),
    CONSTRAINT chk_criterion_other CHECK (
        criterion_type <> 'OTHER' OR description IS NOT NULL),
    -- DEFERRED because saving a tranche replaces its whole criteria list, and
    -- Hibernate issues the new inserts before the orphan deletes.
    CONSTRAINT uq_criteria_tranche_sequence UNIQUE (tranche_id, sequence)
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX idx_criteria_tranche_id ON grant_tranche_criteria(tranche_id);
CREATE INDEX idx_criteria_type_met ON grant_tranche_criteria(criterion_type, met);

-- Back-fill 1: an existing prior-utilisation gate becomes a real threshold
-- criterion.
--
-- met is derived as "the old gate was not blocking": condition_met of 'Met' and
-- 'N/A (first/lump)' both allowed a receipt to be recorded, only 'Pending' held
-- it up. Deriving it from 'Met' alone would newly block first and lump-sum
-- tranches that the old free-text gate deliberately waved through.
INSERT INTO grant_tranche_criteria (
    tranche_id, sequence, criterion_type, utilisation_percent, trigger_basis, description, met)
SELECT t.id, 1, 'UTILISATION_THRESHOLD', t.prior_utilisation_required, 'PREVIOUS_TRANCHE',
       'Migrated from prior_utilisation_required',
       COALESCE(LOWER(t.condition_met) NOT LIKE '%pending%', FALSE)
FROM grant_tranche t
WHERE t.prior_utilisation_required IS NOT NULL
  AND t.prior_utilisation_required > 0
  AND t.prior_utilisation_required <= 100;

-- Back-fill 2: free-text release conditions become an OTHER criterion, numbered
-- after any threshold row already inserted for that tranche.
INSERT INTO grant_tranche_criteria (tranche_id, sequence, criterion_type, description, met)
SELECT t.id,
       COALESCE((SELECT MAX(c.sequence) FROM grant_tranche_criteria c WHERE c.tranche_id = t.id), 0) + 1,
       'OTHER',
       t.conditions_to_release,
       COALESCE(LOWER(t.condition_met) NOT LIKE '%pending%', FALSE)
FROM grant_tranche t
WHERE t.conditions_to_release IS NOT NULL
  AND TRIM(t.conditions_to_release) <> '';
