-- V46: Role directory — resolves a responsible role to a person and a deputy
--      (Disbursement Rules §5: "Role resolves to a person + deputy via the org
--      Role Directory. Deputy is notified only - approval authority does not
--      transfer.").
--
-- Distinct from the `roles` table (V10), which is the auth role vocabulary. This
-- maps an *organisational* role to the humans who hold it, so a reminder has
-- somewhere to go.

CREATE TABLE role_directory (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role            VARCHAR(30) NOT NULL UNIQUE,
    primary_user_id BIGINT,
    deputy_user_id  BIGINT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    CONSTRAINT fk_role_directory_primary FOREIGN KEY (primary_user_id) REFERENCES users(id),
    CONSTRAINT fk_role_directory_deputy FOREIGN KEY (deputy_user_id) REFERENCES users(id),
    CONSTRAINT chk_role_directory_role CHECK (role IN (
        'PROGRAMME_MANAGER', 'CFO', 'HEAD_OF_ORGANISATION', 'ACCOUNTS')),
    -- One person cannot be their own deputy: escalation would be a no-op.
    CONSTRAINT chk_role_directory_distinct CHECK (
        deputy_user_id IS NULL OR primary_user_id IS NULL OR deputy_user_id <> primary_user_id)
);

-- One row per role, holders left unset: assigning real people is an
-- administrative act, and inventing an assignment here would silently point
-- reminders at whoever happened to be seeded first.
INSERT INTO role_directory (role) VALUES
    ('PROGRAMME_MANAGER'),
    ('CFO'),
    ('HEAD_OF_ORGANISATION'),
    ('ACCOUNTS');
