-- V47: Reminder & escalation config, one row per human-actioned criterion
--      (Disbursement Rules §5).
--
-- Only attaches to Milestone Based, UC, Financial Report, Narrative Report,
-- Audit Report and Donor Approval — Utilisation Threshold is auto-checked and On
-- Signing is instant. The application enforces that (CriterionType.humanActioned);
-- the DB enforces the field shapes.
--
-- The due date is NOT stored: it is the tranche's planned_release_date minus
-- reminder_lead_days, computed on read, so moving a tranche date can never leave
-- a stale countdown behind.

CREATE TABLE grant_criteria_reminder (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    criterion_id       BIGINT NOT NULL UNIQUE,
    responsible_role   VARCHAR(30) NOT NULL,
    reminder_lead_days INTEGER NOT NULL,
    repeat_reminder    VARCHAR(20) NOT NULL DEFAULT 'ONCE',
    escalate_to_deputy BOOLEAN NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by         VARCHAR(255),
    updated_by         VARCHAR(255),
    CONSTRAINT fk_reminder_criterion FOREIGN KEY (criterion_id)
        REFERENCES grant_tranche_criteria(id) ON DELETE CASCADE,
    CONSTRAINT chk_reminder_role CHECK (responsible_role IN (
        'PROGRAMME_MANAGER', 'CFO', 'HEAD_OF_ORGANISATION', 'ACCOUNTS')),
    CONSTRAINT chk_reminder_repeat CHECK (repeat_reminder IN ('ONCE', 'EVERY_3_DAYS', 'WEEKLY')),
    CONSTRAINT chk_reminder_lead_days CHECK (reminder_lead_days >= 0 AND reminder_lead_days <= 365)
);

CREATE INDEX idx_reminder_criterion_id ON grant_criteria_reminder(criterion_id);
