-- V48: In-app notifications — the delivery side of reminders & escalation
--      (Disbursement Rules §5).
--
-- Deliberately simple: rows written by the nightly reminder sweep and read by the
-- app's notification list. No email, no push, no per-user preferences.
--
-- dedupe_key makes the sweep idempotent: the same criterion, due date and
-- recipient can only be notified once, so a restart, a re-run or a second app
-- instance cannot double-send. Retro-fitting this after people start trusting
-- reminders is much harder than having it from the start.

CREATE TABLE notification (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL,
    title        VARCHAR(255) NOT NULL,
    body         TEXT,
    -- Where clicking through should land, e.g. '/grants/12/disbursement'.
    link         VARCHAR(500),
    category     VARCHAR(30) NOT NULL DEFAULT 'REMINDER',
    -- FYI copy sent to a deputy; authority does not transfer with it.
    escalation   BOOLEAN NOT NULL DEFAULT FALSE,
    read_at      TIMESTAMP,
    dedupe_key   VARCHAR(255) NOT NULL UNIQUE,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by   VARCHAR(255),
    updated_by   VARCHAR(255),
    CONSTRAINT fk_notification_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT chk_notification_category CHECK (category IN ('REMINDER', 'ESCALATION', 'SYSTEM'))
);

CREATE INDEX idx_notification_user_unread ON notification(user_id, read_at);
CREATE INDEX idx_notification_created ON notification(created_at DESC);
