-- V4: Grant Agreement (Aggregate Root)
CREATE TABLE grant_agreement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grant_code VARCHAR(20) NOT NULL UNIQUE,
    donor_id BIGINT NOT NULL,
    programme_id BIGINT NOT NULL,
    agreement_name VARCHAR(255) NOT NULL,
    agreement_date DATE NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_grant_amount DECIMAL(15, 2) NOT NULL,
    fund_class VARCHAR(50) NOT NULL,
    grant_status VARCHAR(50) DEFAULT 'DRAFT',
    description TEXT,
    agreement_document_path VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_grant_donor FOREIGN KEY (donor_id) REFERENCES donor_master(id),
    CONSTRAINT fk_grant_programme FOREIGN KEY (programme_id) REFERENCES programme(id)
);

-- Create indexes
CREATE INDEX idx_grant_code ON grant_agreement(grant_code);
CREATE INDEX idx_grant_donor_id ON grant_agreement(donor_id);
CREATE INDEX idx_grant_programme_id ON grant_agreement(programme_id);
CREATE INDEX idx_grant_status ON grant_agreement(grant_status);
CREATE INDEX idx_grant_dates ON grant_agreement(start_date, end_date);
