-- V50: Rework the fund-profile subtree to match the reworked Java entities.
--      donor_geography (free-text) -> spendable_geography (state_id FK).
--      fund_profile_tranche (flat plan on the profile) -> donor_tranche_criterion
--      (nested under a disbursement rule, merged with release-criteria fields —
--      see grant_tranche_criteria, V45, for the sibling shape this mirrors).
--      donor_fund_profile.fund_class_code/admin_allowed/overhead_limit_percent are
--      replaced by fund_class (enum). donor_utilisation_rule.rule_type and
--      donor_disbursement_rule's old free-text columns become enum-backed.
--
-- Pre-launch: no production data to preserve. Rows in the tables whose column
-- shapes change incompatibly (donor_utilisation_rule, donor_disbursement_rule)
-- are cleared rather than transformed; fund_mode's title-case seed values are
-- normalised in place since they map 1:1 to the enum's constant names.

-- --------------------------------------------------------------------------
-- Superseded tables
-- --------------------------------------------------------------------------
DROP TABLE IF EXISTS fund_profile_tranche;
DROP TABLE IF EXISTS donor_geography;

-- --------------------------------------------------------------------------
-- donor_fund_profile: fund_class_code/admin_allowed/overhead_limit_percent -> fund_class
-- --------------------------------------------------------------------------
ALTER TABLE donor_fund_profile DROP CONSTRAINT IF EXISTS chk_fund_class_code;
DROP INDEX IF EXISTS idx_profile_class;

ALTER TABLE donor_fund_profile
    DROP COLUMN IF EXISTS fund_class_code,
    DROP COLUMN IF EXISTS admin_allowed,
    DROP COLUMN IF EXISTS overhead_limit_percent,
    ADD COLUMN fund_class VARCHAR(30);

ALTER TABLE donor_fund_profile ADD CONSTRAINT chk_fund_class
    CHECK (fund_class IS NULL OR fund_class IN
        ('CLASS_A_RESTRICTED', 'CLASS_B_UNRESTRICTED', 'CLASS_C_UNRESTRICTED'));

CREATE INDEX idx_profile_class ON donor_fund_profile(fund_class);

-- Legacy seed data stored 'Restricted'/'Unrestricted'; the enum's persisted
-- name is 'RESTRICTED'/'UNRESTRICTED'.
UPDATE donor_fund_profile SET fund_mode = UPPER(fund_mode) WHERE fund_mode IS NOT NULL;

ALTER TABLE donor_fund_profile ADD CONSTRAINT chk_fund_mode
    CHECK (fund_mode IS NULL OR fund_mode IN ('UNRESTRICTED', 'RESTRICTED'));

-- Legacy seed data stored 'Quarterly'/'Half-yearly'/'Annual'; the enum's
-- persisted names are 'QUARTERLY'/'HALF_YEARLY'/'ANNUAL'.
UPDATE donor_fund_profile SET reporting_frequency = UPPER(REPLACE(reporting_frequency, '-', '_'))
WHERE reporting_frequency IS NOT NULL;

ALTER TABLE donor_fund_profile ADD CONSTRAINT chk_reporting_frequency
    CHECK (reporting_frequency IS NULL OR reporting_frequency IN ('QUARTERLY', 'HALF_YEARLY', 'ANNUAL'));

-- --------------------------------------------------------------------------
-- donor_utilisation_rule: free-text rule_type -> enum; add other_rule_type
-- --------------------------------------------------------------------------
DELETE FROM donor_utilisation_rule;

ALTER TABLE donor_utilisation_rule
    ADD CONSTRAINT chk_util_rule_type CHECK (rule_type IN
        ('ADMIN_OVERHEAD_COST', 'NOT_APPLICABLE', 'OTHER_CUSTOM')),
    ADD COLUMN other_rule_type VARCHAR(50);

-- --------------------------------------------------------------------------
-- donor_disbursement_rule: old rule_type/release_trigger/... -> total_amount + disbursement_type
-- --------------------------------------------------------------------------
DELETE FROM donor_disbursement_rule;

ALTER TABLE donor_disbursement_rule
    DROP COLUMN IF EXISTS rule_type,
    DROP COLUMN IF EXISTS release_trigger,
    DROP COLUMN IF EXISTS min_prior_utilisation_required,
    DROP COLUMN IF EXISTS milestone_required,
    DROP COLUMN IF EXISTS rule_description,
    ADD COLUMN total_amount DECIMAL(19, 2),
    ADD COLUMN disbursement_type VARCHAR(50) NOT NULL;

ALTER TABLE donor_disbursement_rule ADD CONSTRAINT chk_disb_type
    CHECK (disbursement_type IN ('LUMP_SUM', 'TRANCHES'));

-- --------------------------------------------------------------------------
-- donor_tranche_criterion (new) — one row per planned release, merging the old
-- fund_profile_tranche's amount/date with a grant_tranche_criteria-style
-- release-criteria row. Mirrors V45's per-type CHECK-constraint style.
-- --------------------------------------------------------------------------
CREATE TABLE donor_tranche_criterion (
    id                                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disbursement_rule_id              BIGINT NOT NULL,
    amount_criteria                   DECIMAL(19, 2) NOT NULL,
    expected_release_date             DATE,
    frequency                         VARCHAR(50) NOT NULL DEFAULT 'MONTHLY',
    is_final_tranche                  BOOLEAN DEFAULT FALSE,
    -- TEXT to match the entity's columnDefinition="TEXT" on this column (an
    -- inconsistency versus every other enum column here, which are VARCHAR).
    release_criteria                  TEXT,
    release_date                      DATE,
    -- DOUBLE PRECISION, not NUMERIC: the entity field is a Java Double, which
    -- Hibernate maps to a floating-point SQL type (precision/scale are only
    -- valid for a BigDecimal-backed column).
    utilisation_percentage            DOUBLE PRECISION,
    trigger_basis                     VARCHAR(50),
    description                       TEXT,
    milestone_name                    VARCHAR(100),
    verification_sign_off_role        VARCHAR(50),
    other_verification_sign_off_role  VARCHAR(100),
    trigger_date                      DATE,
    remind_someone                    BOOLEAN DEFAULT FALSE,
    responsible_role                  VARCHAR(50),
    other_responsible_role            VARCHAR(100),
    reminder_lead_time                INTEGER,
    repeat_reminder                   VARCHAR(50),
    escalate_to_deputy                BOOLEAN DEFAULT FALSE,
    created_at                        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by                        VARCHAR(255),
    updated_by                        VARCHAR(255),
    CONSTRAINT fk_criterion_disb_rule FOREIGN KEY (disbursement_rule_id)
        REFERENCES donor_disbursement_rule(id) ON DELETE CASCADE,
    CONSTRAINT chk_donor_criterion_amount CHECK (amount_criteria > 0),
    CONSTRAINT chk_donor_criterion_frequency CHECK (frequency IN
        ('MONTHLY', 'QUARTERLY', 'HALF_YEARLY', 'YEARLY')),
    CONSTRAINT chk_donor_criterion_release_criteria CHECK (release_criteria IS NULL OR release_criteria IN (
        'ON_SIGNING', 'FIXED_DATE', 'MILESTONE_BASED', 'UTILISATION_THRESHOLD',
        'UTILISATION_CERTIFICATE', 'FINANCIAL_REPORT', 'NARRATIVE_REPORT',
        'AUDIT_REPORT', 'DONOR_APPROVAL', 'OTHER')),
    -- Both verification_sign_off_role and responsible_role are typed
    -- VerificationRole on this entity (unlike the grant side's separate,
    -- narrower ResponsibleRole) — reflected here, not "corrected" to match.
    CONSTRAINT chk_donor_criterion_verification_role CHECK (verification_sign_off_role IS NULL OR
        verification_sign_off_role IN ('CEO', 'CFO', 'PROGRAMME_MANAGER', 'HEAD_OF_ORGANISATION', 'OTHER')),
    CONSTRAINT chk_donor_criterion_responsible_role CHECK (responsible_role IS NULL OR
        responsible_role IN ('CEO', 'CFO', 'PROGRAMME_MANAGER', 'HEAD_OF_ORGANISATION', 'OTHER')),
    CONSTRAINT chk_donor_criterion_trigger_basis CHECK (trigger_basis IS NULL OR
        trigger_basis IN ('PREVIOUS_TRANCHE', 'CUMULATIVE')),
    CONSTRAINT chk_donor_criterion_repeat_reminder CHECK (repeat_reminder IS NULL OR
        repeat_reminder IN ('ONCE', 'EVERY_3_DAYS', 'WEEKLY')),
    CONSTRAINT chk_donor_criterion_utilisation_pct CHECK (utilisation_percentage IS NULL OR
        (utilisation_percentage > 0 AND utilisation_percentage <= 100)),
    CONSTRAINT chk_donor_criterion_fixed_date CHECK (
        release_criteria <> 'FIXED_DATE' OR release_date IS NOT NULL),
    CONSTRAINT chk_donor_criterion_milestone CHECK (
        release_criteria <> 'MILESTONE_BASED'
        OR (milestone_name IS NOT NULL AND verification_sign_off_role IS NOT NULL)),
    CONSTRAINT chk_donor_criterion_threshold CHECK (
        release_criteria <> 'UTILISATION_THRESHOLD'
        OR (utilisation_percentage IS NOT NULL AND trigger_basis IS NOT NULL)),
    CONSTRAINT chk_donor_criterion_other CHECK (
        release_criteria <> 'OTHER' OR description IS NOT NULL)
);

CREATE INDEX idx_criterion_disb_rule_id ON donor_tranche_criterion(disbursement_rule_id);
CREATE INDEX idx_criterion_release_criteria ON donor_tranche_criterion(release_criteria);

-- --------------------------------------------------------------------------
-- spendable_geography (new) — replaces donor_geography's free text with a
-- real state reference.
-- --------------------------------------------------------------------------
CREATE TABLE spendable_geography (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fund_profile_id BIGINT NOT NULL,
    state_id        BIGINT NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    CONSTRAINT fk_geo_profile FOREIGN KEY (fund_profile_id)
        REFERENCES donor_fund_profile(id) ON DELETE CASCADE,
    CONSTRAINT fk_donation_location_state FOREIGN KEY (state_id) REFERENCES state_master(id),
    CONSTRAINT uq_geo_profile_state UNIQUE (fund_profile_id, state_id)
);

CREATE INDEX idx_geo_profile_id ON spendable_geography(fund_profile_id);
CREATE INDEX idx_geo_state_id ON spendable_geography(state_id);
