-- V41: Bring the fund-profile rule subtree in line with the current entities.
--
-- donor_geography (free-text geography name) is replaced by spendable_location
-- (a real FK to state_master); donor_disbursement_rule moves from a flat
-- rule-type row to a schedule header (total committed + LUMP_SUM/TRANCHE) that
-- owns a donor_tranche_detail per release; donor_utilisation_rule gains the
-- free-text "other" companion column used when rule_type = OTHER_CUSTOM.
--
-- donor_geography itself is left in place, unmapped and unused, rather than
-- dropped: its rows are free-text and have no reliable mapping to a
-- state_master row, so there is nothing safe to migrate forward.

CREATE TABLE spendable_location (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_fund_profile_id BIGINT NOT NULL,
    state_id              BIGINT NOT NULL,
    created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by            VARCHAR(255),
    updated_by            VARCHAR(255),
    CONSTRAINT fk_spendable_location_donor_fund_profile FOREIGN KEY (donor_fund_profile_id) REFERENCES donor_fund_profile(id) ON DELETE CASCADE,
    CONSTRAINT fk_spendable_location_state FOREIGN KEY (state_id) REFERENCES state_master(id)
);
CREATE INDEX idx_spendable_location_profile_id ON spendable_location(donor_fund_profile_id);

ALTER TABLE donor_utilisation_rule
    ADD COLUMN other_rule_type VARCHAR(50);

ALTER TABLE donor_disbursement_rule
    DROP COLUMN rule_type,
    DROP COLUMN release_trigger,
    DROP COLUMN min_prior_utilisation_required,
    DROP COLUMN milestone_required,
    DROP COLUMN rule_description,
    ADD COLUMN total_amount_committed VARCHAR(50) NOT NULL DEFAULT '0',
    ADD COLUMN disbursement_type VARCHAR(20) NOT NULL DEFAULT 'LUMP_SUM';

ALTER TABLE donor_disbursement_rule
    ALTER COLUMN total_amount_committed DROP DEFAULT,
    ALTER COLUMN disbursement_type DROP DEFAULT;

CREATE TABLE donor_tranche_detail (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disbursement_rule_id   BIGINT NOT NULL,
    amount                 VARCHAR(50) NOT NULL,
    frequency              VARCHAR(20) NOT NULL,
    is_final_tranche       BOOLEAN NOT NULL DEFAULT FALSE,
    release_criteria       VARCHAR(30) NOT NULL,
    release_date           DATE,
    milestone_name         VARCHAR(255),
    sign_of_role           VARCHAR(30),
    other_sign_of_role     VARCHAR(255),
    target_date            DATE,
    utilisation_percentage VARCHAR(10),
    trigger_base           VARCHAR(30),
    description            TEXT,
    responsible_role       VARCHAR(30),
    other_responsible_role VARCHAR(255),
    reminder_lead_time     VARCHAR(20),
    repeat_reminder        VARCHAR(30),
    escalate_to_deputy     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at             TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by             VARCHAR(255),
    updated_by             VARCHAR(255),
    CONSTRAINT fk_tranche_detail_disbursement_rule FOREIGN KEY (disbursement_rule_id) REFERENCES donor_disbursement_rule(id) ON DELETE CASCADE
);
CREATE INDEX idx_tranche_detail_disbursement_rule_id ON donor_tranche_detail(disbursement_rule_id);
