-- V53: Split the release-criteria fields out of donor_tranche_criterion into
-- their own donor_release_criteria table, mirroring the entity split
-- (DonorTrancheCriterion is now just the tranche: amount/date/frequency;
-- DonorReleaseCriteria is one gate on it, one-to-many so a tranche can carry
-- more than one release condition).
--
-- Pre-launch: no production data to preserve (same convention as V50) — the
-- moved columns are dropped rather than backfilled into the new table.

ALTER TABLE donor_tranche_criterion
    DROP CONSTRAINT IF EXISTS chk_donor_criterion_release_criteria,
    DROP CONSTRAINT IF EXISTS chk_donor_criterion_verification_role,
    DROP CONSTRAINT IF EXISTS chk_donor_criterion_responsible_role,
    DROP CONSTRAINT IF EXISTS chk_donor_criterion_trigger_basis,
    DROP CONSTRAINT IF EXISTS chk_donor_criterion_repeat_reminder,
    DROP CONSTRAINT IF EXISTS chk_donor_criterion_utilisation_pct,
    DROP CONSTRAINT IF EXISTS chk_donor_criterion_fixed_date,
    DROP CONSTRAINT IF EXISTS chk_donor_criterion_milestone,
    DROP CONSTRAINT IF EXISTS chk_donor_criterion_threshold,
    DROP CONSTRAINT IF EXISTS chk_donor_criterion_other;

DROP INDEX IF EXISTS idx_criterion_release_criteria;

ALTER TABLE donor_tranche_criterion
    DROP COLUMN IF EXISTS release_criteria,
    DROP COLUMN IF EXISTS release_date,
    DROP COLUMN IF EXISTS utilisation_percentage,
    DROP COLUMN IF EXISTS trigger_basis,
    DROP COLUMN IF EXISTS description,
    DROP COLUMN IF EXISTS milestone_name,
    DROP COLUMN IF EXISTS verification_sign_off_role,
    DROP COLUMN IF EXISTS other_verification_sign_off_role,
    DROP COLUMN IF EXISTS trigger_date,
    DROP COLUMN IF EXISTS remind_someone,
    DROP COLUMN IF EXISTS responsible_role,
    DROP COLUMN IF EXISTS other_responsible_role,
    DROP COLUMN IF EXISTS reminder_lead_time,
    DROP COLUMN IF EXISTS repeat_reminder,
    DROP COLUMN IF EXISTS escalate_to_deputy;

CREATE TABLE donor_release_criteria (
    id                                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tranche_criterion_id              BIGINT NOT NULL,
    -- TEXT to match the entity's columnDefinition="TEXT", carried over as-is
    -- from the column this replaces on donor_tranche_criterion.
    release_criteria                  TEXT,
    release_date                      DATE,
    utilisation_percentage            DOUBLE PRECISION,
    trigger_basis                     VARCHAR(50),
    description                       TEXT,
    milestone_name                    VARCHAR(100),
    verification_sign_off_role        VARCHAR(50),
    other_verification_sign_off_role  VARCHAR(100),
    trigger_date                      DATE,
    remind_someone                    BOOLEAN DEFAULT FALSE,
    responsible_role                  VARCHAR(50),
    other_responsible_role            VARCHAR(100),
    reminder_lead_time                INTEGER,
    repeat_reminder                   VARCHAR(50),
    escalate_to_deputy                BOOLEAN DEFAULT FALSE,
    created_at                        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by                        VARCHAR(255),
    updated_by                        VARCHAR(255),
    CONSTRAINT fk_release_criteria_tranche_criterion FOREIGN KEY (tranche_criterion_id)
        REFERENCES donor_tranche_criterion(id) ON DELETE CASCADE,
    CONSTRAINT chk_release_criteria_type CHECK (release_criteria IS NULL OR release_criteria IN (
        'ON_SIGNING', 'FIXED_DATE', 'MILESTONE_BASED', 'UTILISATION_THRESHOLD',
        'UTILISATION_CERTIFICATE', 'FINANCIAL_REPORT', 'NARRATIVE_REPORT',
        'AUDIT_REPORT', 'DONOR_APPROVAL', 'OTHER')),
    -- Both role columns are typed VerificationRole on this entity (unlike the
    -- grant side's separate, narrower ResponsibleRole) — carried over as-is.
    CONSTRAINT chk_release_criteria_verification_role CHECK (verification_sign_off_role IS NULL OR
        verification_sign_off_role IN ('CEO', 'CFO', 'PROGRAMME_MANAGER', 'HEAD_OF_ORGANISATION', 'OTHER')),
    CONSTRAINT chk_release_criteria_responsible_role CHECK (responsible_role IS NULL OR
        responsible_role IN ('CEO', 'CFO', 'PROGRAMME_MANAGER', 'HEAD_OF_ORGANISATION', 'OTHER')),
    CONSTRAINT chk_release_criteria_trigger_basis CHECK (trigger_basis IS NULL OR
        trigger_basis IN ('PREVIOUS_TRANCHE', 'CUMULATIVE')),
    CONSTRAINT chk_release_criteria_repeat_reminder CHECK (repeat_reminder IS NULL OR
        repeat_reminder IN ('ONCE', 'EVERY_3_DAYS', 'WEEKLY')),
    CONSTRAINT chk_release_criteria_utilisation_pct CHECK (utilisation_percentage IS NULL OR
        (utilisation_percentage > 0 AND utilisation_percentage <= 100)),
    CONSTRAINT chk_release_criteria_fixed_date CHECK (
        release_criteria <> 'FIXED_DATE' OR release_date IS NOT NULL),
    CONSTRAINT chk_release_criteria_milestone CHECK (
        release_criteria <> 'MILESTONE_BASED'
        OR (milestone_name IS NOT NULL AND verification_sign_off_role IS NOT NULL)),
    CONSTRAINT chk_release_criteria_threshold CHECK (
        release_criteria <> 'UTILISATION_THRESHOLD'
        OR (utilisation_percentage IS NOT NULL AND trigger_basis IS NOT NULL)),
    CONSTRAINT chk_release_criteria_other CHECK (
        release_criteria <> 'OTHER' OR description IS NOT NULL)
);

CREATE INDEX idx_release_criteria_tranche_criterion_id ON donor_release_criteria(tranche_criterion_id);
CREATE INDEX idx_release_criteria_type ON donor_release_criteria(release_criteria);
