-- V56: Create organisation_register table for partner organisation registration
CREATE TABLE organisation_register (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    short_name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL,
    web_url VARCHAR(255),
    address1 TEXT NOT NULL,
    address2 TEXT,
    city_id BIGINT NOT NULL,
    state_id BIGINT NOT NULL,
    zip_code VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_organisation_city FOREIGN KEY (city_id) REFERENCES city_master(id),
    CONSTRAINT fk_organisation_state FOREIGN KEY (state_id) REFERENCES state_master(id)
);

CREATE INDEX idx_organisation_register_email ON organisation_register(email);
CREATE INDEX idx_organisation_register_status ON organisation_register(status);
CREATE INDEX idx_organisation_register_city_id ON organisation_register(city_id);
CREATE INDEX idx_organisation_register_state_id ON organisation_register(state_id);
