-- V59: Role master — an admin-managed catalog of organisational role names
--      (Role Directory screen): role name, short name, and Active/Inactive
--      status. Distinct from `roles` (V10, the auth role vocabulary) and
--      from `role_directory` (V46, the role-to-person+deputy assignment
--      table used for disbursement reminder routing).
CREATE TABLE role_master (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name   VARCHAR(255) NOT NULL UNIQUE,
    short_name  VARCHAR(50) NOT NULL UNIQUE,
    status      VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255)
);

CREATE INDEX idx_role_master_status ON role_master(status);
