-- V5: Grant Rules, Reporting, and Geography
CREATE TABLE grant_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grant_id BIGINT NOT NULL,
    rule_code VARCHAR(50) NOT NULL,
    rule_name VARCHAR(255) NOT NULL,
    rule_type VARCHAR(100) NOT NULL,
    rule_definition TEXT NOT NULL,
    rule_value VARCHAR(500),
    is_mandatory BOOLEAN DEFAULT FALSE,
    rule_status VARCHAR(50) DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_rule_grant FOREIGN KEY (grant_id) REFERENCES grant_agreement(id) ON DELETE CASCADE
);

CREATE TABLE grant_reporting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grant_id BIGINT NOT NULL,
    reporting_schedule_id BIGINT NOT NULL,
    reporting_frequency VARCHAR(50) NOT NULL,
    report_due_days INT NOT NULL,
    last_report_date TIMESTAMP,
    next_report_date TIMESTAMP,
    reporting_status VARCHAR(50) DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_reporting_grant FOREIGN KEY (grant_id) REFERENCES grant_agreement(id) ON DELETE CASCADE,
    CONSTRAINT fk_reporting_schedule FOREIGN KEY (reporting_schedule_id) REFERENCES reporting_schedule_master(id)
);

CREATE TABLE grant_geography (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grant_id BIGINT NOT NULL,
    state_id BIGINT,
    district_id BIGINT,
    city_id BIGINT,
    coverage_area_percentage DECIMAL(5, 2),
    priority_level INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_geography_grant FOREIGN KEY (grant_id) REFERENCES grant_agreement(id) ON DELETE CASCADE,
    CONSTRAINT fk_geography_state FOREIGN KEY (state_id) REFERENCES state_master(id),
    CONSTRAINT fk_geography_district FOREIGN KEY (district_id) REFERENCES district_master(id),
    CONSTRAINT fk_geography_city FOREIGN KEY (city_id) REFERENCES city_master(id)
);

-- Create indexes
CREATE INDEX idx_rule_grant_id ON grant_rule(grant_id);
CREATE INDEX idx_reporting_grant_id ON grant_reporting(grant_id);
CREATE INDEX idx_geography_grant_id ON grant_geography(grant_id);
CREATE INDEX idx_geography_state_id ON grant_geography(state_id);
