-- V62: Join table assigning users to a role_master entry, so the Role
--      Directory can track and cap how many users hold a given role
--      (role_master.user_limit).
CREATE TABLE role_master_user (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_master_id BIGINT NOT NULL,
    user_id        BIGINT NOT NULL,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    CONSTRAINT fk_role_master_user_role FOREIGN KEY (role_master_id) REFERENCES role_master(id),
    CONSTRAINT fk_role_master_user_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT uk_role_master_user UNIQUE (role_master_id, user_id)
);

CREATE INDEX idx_role_master_user_role_master_id ON role_master_user(role_master_id);
CREATE INDEX idx_role_master_user_user_id ON role_master_user(user_id);
