-- V63: Extended registration (register-extended) — a standalone table for
--      the userRegisterNew module, independent of the legacy `users` table
--      (userRegister module). Captures the applicant's account details plus
--      the selected Role Directory role and Organisation Register entry as
--      plain FK id columns (repo convention, see role_master_user.user_id).
CREATE TABLE user_register_new (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name       VARCHAR(255) NOT NULL,
    last_name        VARCHAR(255),
    email_id         VARCHAR(255) NOT NULL UNIQUE,
    mobile_no        VARCHAR(10) NOT NULL UNIQUE,
    username         VARCHAR(20) NOT NULL UNIQUE,
    password         VARCHAR(255) NOT NULL,
    role_id          BIGINT NOT NULL,
    organisation_id  BIGINT NOT NULL,
    status           BOOLEAN NOT NULL DEFAULT true,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by       VARCHAR(255),
    updated_by       VARCHAR(255),
    CONSTRAINT username_length CHECK (LENGTH(username) >= 4 AND LENGTH(username) <= 20),
    CONSTRAINT password_length CHECK (LENGTH(password) >= 8 AND LENGTH(password) <= 100),
    CONSTRAINT fk_user_register_new_role FOREIGN KEY (role_id) REFERENCES role_master(id),
    CONSTRAINT fk_user_register_new_organisation FOREIGN KEY (organisation_id) REFERENCES organization_register(id)
);

CREATE INDEX idx_user_register_new_email ON user_register_new(email_id);
CREATE INDEX idx_user_register_new_username ON user_register_new(username);
CREATE INDEX idx_user_register_new_role_id ON user_register_new(role_id);
CREATE INDEX idx_user_register_new_organisation_id ON user_register_new(organisation_id);
