-- V67: Payment mode master — supported financial instruments and payment
--      methods (Cash, Cheque, NEFT, RTGS, UPI, ...) selectable on transaction
--      entries.
CREATE TABLE payment_mode (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    status      BOOLEAN NOT NULL DEFAULT true,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255)
);

CREATE INDEX idx_payment_mode_status ON payment_mode(status);

INSERT INTO payment_mode (name, status) VALUES
('Cash', true),
('Cheque', true),
('NEFT', true),
('RTGS', true),
('IMPS', true),
('UPI', true),
('Card', true),
('Demand Draft', true),
('Auto-debit (NACH)', true),
('In-kind (non-cash)', true);
