-- V68: Vendor / Supplier register. Entity Type drives which identification,
--      tax and document fields are meaningful for a given vendor (Individual
--      vendors use Aadhaar in place of company registration and skip
--      GST/TAN/Udyam) — enforced in the service layer, not by DB constraints.
--      vendor_code is assigned after the initial insert (VEN-<id>), so the
--      column starts nullable and is backfilled by the application.
CREATE TABLE vendor_register (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_code                     VARCHAR(20) UNIQUE,
    entity_type                     VARCHAR(20) NOT NULL,
    legal_name                      VARCHAR(255) NOT NULL,
    has_incorporation_certificate   VARCHAR(3),
    date_of_incorporation           DATE,
    registration_no                 VARCHAR(50),
    aadhaar_number                  VARCHAR(12),
    pan_number                      VARCHAR(10) NOT NULL UNIQUE,
    has_gst_registration            VARCHAR(3),
    gst_number                      VARCHAR(15),
    gst_registration_type           VARCHAR(20),
    tan_number                      VARCHAR(10),
    has_msme_registration           VARCHAR(3),
    udyam_number                    VARCHAR(30),
    enterprise_classification       VARCHAR(10),
    tds_section                     VARCHAR(5) NOT NULL,
    account_number                  VARCHAR(30) NOT NULL,
    ifsc_code                       VARCHAR(11) NOT NULL,
    account_holder_name             VARCHAR(255) NOT NULL,
    bank_name                       VARCHAR(255),
    branch_name                     VARCHAR(255),
    payment_mode                    VARCHAR(10) NOT NULL,
    contact_name                    VARCHAR(255) NOT NULL,
    phone_number                    VARCHAR(10) NOT NULL,
    contact_email                   VARCHAR(255) NOT NULL,
    registered_address              TEXT NOT NULL,
    state                           VARCHAR(100) NOT NULL,
    pincode                         VARCHAR(6) NOT NULL,
    vendor_category                 VARCHAR(30) NOT NULL,
    related_party                   VARCHAR(3) NOT NULL,
    status                          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at                      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by                      VARCHAR(255),
    updated_by                      VARCHAR(255)
);

CREATE INDEX idx_vendor_register_status ON vendor_register(status);
CREATE INDEX idx_vendor_register_entity_type ON vendor_register(entity_type);
