-- V6: Grant Tranches, Documents, Budget Heads, KPI
CREATE TABLE grant_tranche (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grant_id BIGINT NOT NULL,
    tranche_number INT NOT NULL,
    tranche_name VARCHAR(255),
    tranche_amount DECIMAL(15, 2) NOT NULL,
    planned_release_date DATE,
    actual_release_date DATE,
    conditions_to_release TEXT,
    tranche_status VARCHAR(50) DEFAULT 'PENDING',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_tranche_grant FOREIGN KEY (grant_id) REFERENCES grant_agreement(id) ON DELETE CASCADE
);

CREATE TABLE grant_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grant_id BIGINT NOT NULL,
    document_name VARCHAR(255) NOT NULL,
    document_type VARCHAR(100) NOT NULL,
    document_path VARCHAR(500) NOT NULL,
    file_size BIGINT,
    mime_type VARCHAR(100),
    version INT DEFAULT 1,
    is_current BOOLEAN DEFAULT TRUE,
    upload_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_document_grant FOREIGN KEY (grant_id) REFERENCES grant_agreement(id) ON DELETE CASCADE
);

CREATE TABLE grant_budget_head (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grant_id BIGINT NOT NULL,
    head_code VARCHAR(50) NOT NULL,
    head_name VARCHAR(255) NOT NULL,
    budgeted_amount DECIMAL(15, 2) NOT NULL,
    spent_amount DECIMAL(15, 2) DEFAULT 0,
    percentage_spent DECIMAL(5, 2) DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_budget_grant FOREIGN KEY (grant_id) REFERENCES grant_agreement(id) ON DELETE CASCADE
);

CREATE TABLE grant_kpi (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grant_id BIGINT NOT NULL,
    kpi_code VARCHAR(50) NOT NULL,
    kpi_name VARCHAR(255) NOT NULL,
    kpi_unit VARCHAR(100),
    target_value DECIMAL(15, 2) NOT NULL,
    current_value DECIMAL(15, 2) DEFAULT 0,
    performance_percentage DECIMAL(5, 2) DEFAULT 0,
    data_type VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    CONSTRAINT fk_kpi_grant FOREIGN KEY (grant_id) REFERENCES grant_agreement(id) ON DELETE CASCADE
);

-- Create indexes
CREATE INDEX idx_tranche_grant_id ON grant_tranche(grant_id);
CREATE INDEX idx_tranche_status ON grant_tranche(tranche_status);
CREATE INDEX idx_document_grant_id ON grant_document(grant_id);
CREATE INDEX idx_document_type ON grant_document(document_type);
CREATE INDEX idx_budget_grant_id ON grant_budget_head(grant_id);
CREATE INDEX idx_kpi_grant_id ON grant_kpi(grant_id);
