-- V70: Department master — organisational department master data used to
--      classify designations under Master Configuration.
CREATE TABLE department (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    status      BOOLEAN NOT NULL DEFAULT true,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255)
);

CREATE INDEX idx_department_status ON department(status);

INSERT INTO department (name, status) VALUES
('DEPT-LEADERSHIP', true),
('DEPT-PROCESS', true),
('DEPT-SPP', true),
('DEPT-PMU-CPCB', true),
('DEPT-OPERATIONS', false),
('DEPT-COMMUNICATIONS', true);
