-- V71: Designation master — job titles tied to a department, selectable
--      wherever an employee's designation is captured.
CREATE TABLE designation (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(255) NOT NULL,
    department_id  BIGINT NOT NULL REFERENCES department(id),
    status         BOOLEAN NOT NULL DEFAULT true,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    CONSTRAINT uq_designation_name_department UNIQUE (name, department_id)
);

CREATE INDEX idx_designation_status ON designation(status);
CREATE INDEX idx_designation_department_id ON designation(department_id);

INSERT INTO designation (name, department_id, status)
SELECT v.name, d.id, v.status
FROM (VALUES
    ('Chief Executive Officer', 'DEPT-LEADERSHIP', true),
    ('Head of Finance', 'DEPT-LEADERSHIP', true),
    ('Head of Fundraising', 'DEPT-LEADERSHIP', true),
    ('Technology Lead', 'DEPT-PROCESS', true),
    ('Finance Manager', 'DEPT-LEADERSHIP', true),
    ('HR & Administration Manager', 'DEPT-OPERATIONS', true),
    ('Accounts Executive', 'DEPT-LEADERSHIP', true),
    ('Compliance Consultant', 'DEPT-PROCESS', true),
    ('Policy Lead', 'DEPT-SPP', true),
    ('Senior Policy Associate', 'DEPT-SPP', true),
    ('Research Associate', 'DEPT-PMU-CPCB', true),
    ('Senior Programme Manager', 'DEPT-SPP', true),
    ('Intern / Volunteer', 'DEPT-COMMUNICATIONS', false)
) AS v(name, dept_name, status)
JOIN department d ON d.name = v.dept_name;
