-- V72: Financial year master — the organisation's accounting periods
--      (typically Apr–Mar cycles) used to scope budgets, transactions and
--      reporting. Exactly one row may be marked current at a time.
CREATE TABLE financial_year (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50) NOT NULL UNIQUE,
    start_date  DATE NOT NULL,
    end_date    DATE NOT NULL,
    is_current  BOOLEAN NOT NULL DEFAULT false,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    CONSTRAINT chk_financial_year_dates CHECK (end_date >= start_date)
);

CREATE UNIQUE INDEX uq_financial_year_current ON financial_year(is_current) WHERE is_current = true;

INSERT INTO financial_year (code, start_date, end_date, is_current) VALUES
('FY 2024-25', '2024-04-01', '2025-03-31', false),
('FY 2025-26', '2025-04-01', '2026-03-31', true),
('FY 2026-27', '2026-04-01', '2027-03-31', false);
