-- V73: Bank details master — statutory bank accounts, each associated with
--      a domestic (LC) or foreign (FC) book.
CREATE TABLE bank_details (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book            VARCHAR(5) NOT NULL,
    bank_name       VARCHAR(255) NOT NULL,
    account_number  VARCHAR(30) NOT NULL UNIQUE,
    ifsc            VARCHAR(11) NOT NULL,
    branch_name     VARCHAR(255) NOT NULL,
    status          BOOLEAN NOT NULL DEFAULT true,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255),
    CONSTRAINT chk_bank_details_book CHECK (book IN ('LC', 'FC'))
);

CREATE INDEX idx_bank_details_status ON bank_details(status);
CREATE INDEX idx_bank_details_book ON bank_details(book);

INSERT INTO bank_details (book, bank_name, account_number, ifsc, branch_name, status) VALUES
('LC', 'HDFC Bank', '50200088201412', 'HDFC0000083', 'GK-1 Branch, New Delhi', true),
('FC', 'State Bank of India', '40192039912041', 'SBIN0000691', 'NDMB Parliament Street, New Delhi', true),
('LC', 'ICICI Bank', '00210533428910', 'ICIC0000021', 'Barakhamba Road Branch, New Delhi', true),
('FC', 'HDFC Bank', '50200055410982', 'HDFC0000240', 'Vasant Vihar Branch, New Delhi', true),
('LC', 'Axis Bank', '918020077194821', 'UTIB0000015', 'Green Park Branch, New Delhi', true),
('FC', 'Standard Chartered Bank', '22105810841920', 'SCBL0036001', 'Connaught Place Branch, New Delhi', true);
