-- V74: Employee master — department and state map to F4 cost centres;
--      bucket determines which F3 ledger the employee's cost posts to
--      (Project buckets additionally carry a primary programme).
CREATE TABLE employee (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id              VARCHAR(20) NOT NULL UNIQUE,
    name                VARCHAR(255) NOT NULL,
    department          VARCHAR(50) NOT NULL,
    designation         VARCHAR(255) NOT NULL,
    bucket              VARCHAR(20) NOT NULL,
    primary_programme   VARCHAR(20),
    state               VARCHAR(100) NOT NULL,
    annual_ctc          NUMERIC(15, 2) NOT NULL,
    employment_type     VARCHAR(20) NOT NULL,
    pf                  VARCHAR(3) NOT NULL,
    esi                 VARCHAR(3) NOT NULL,
    gratuity            VARCHAR(3) NOT NULL,
    status              BOOLEAN NOT NULL DEFAULT true,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255)
);

CREATE INDEX idx_employee_status ON employee(status);
CREATE INDEX idx_employee_department ON employee(department);

INSERT INTO employee (emp_id, name, department, designation, bucket, primary_programme, state, annual_ctc, employment_type, pf, esi, gratuity, status) VALUES
('EMP-01', 'Mohit Beotra', 'DEPT-LEADERSHIP', 'Chief Executive Officer', 'Admin', 'PP6', 'Delhi', 4200000, 'Permanent', 'Yes', 'No', 'Yes', true),
('EMP-02', 'Shanthi Raghavan', 'DEPT-LEADERSHIP', 'Head of Finance', 'Admin', 'PP6', 'Delhi', 2800000, 'Permanent', 'Yes', 'No', 'Yes', true),
('EMP-03', 'Pooja Gill', 'DEPT-LEADERSHIP', 'Head of Fundraising', 'Admin', 'PP6', 'Delhi', 2400000, 'Permanent', 'Yes', 'No', 'Yes', true),
('EMP-04', 'Sandeep Zutshi', 'DEPT-LEADERSHIP', 'Technology Lead', 'Admin', 'PP6', 'Delhi', 2200000, 'Permanent', 'Yes', 'No', 'Yes', true),
('EMP-05', 'Nidhi Mishra', 'DEPT-PROCESS', 'Finance Manager', 'Admin', 'PP6', 'Delhi', 1500000, 'Permanent', 'Yes', 'No', 'Yes', true),
('EMP-06', 'Akansha Bhatt', 'DEPT-PROCESS', 'HR & Administration Manager', 'Admin', 'PP6', 'Delhi', 1300000, 'Permanent', 'Yes', 'Yes', 'Yes', true),
('EMP-07', 'Ritu Sharma', 'DEPT-PROCESS', 'Accounts Executive', 'Admin', 'PP6', 'Delhi', 800000, 'Permanent', 'Yes', 'Yes', 'Yes', true),
('EMP-08', 'Vikas Sethi', 'DEPT-PROCESS', 'Compliance Consultant', 'Admin', 'PP6', 'Delhi', 900000, 'Contract', 'No', 'No', 'No', false),
('EMP-09', 'Kritika Chaudhary', 'DEPT-SPP', 'Policy Lead', 'Project', 'PP1', 'Delhi', 2400000, 'Permanent', 'Yes', 'No', 'Yes', true),
('EMP-10', 'Suhita Dugar', 'DEPT-SPP', 'Senior Policy Associate', 'Project', 'PP1', 'Delhi', 1500000, 'Permanent', 'Yes', 'No', 'Yes', true),
('EMP-11', 'Kshirin Rao', 'DEPT-SPP', 'Research Associate', 'Project', 'PP1', 'Delhi', 900000, 'Permanent', 'Yes', 'No', 'Yes', true),
('EMP-12', 'Pankaj Verma', 'DEPT-PMU-CPCB', 'Senior Programme Manager', 'Project', 'PP1', 'Delhi', 1800000, 'Permanent', 'Yes', 'No', 'Yes', true);
