-- V79: Employee update log — one immutable row per changed field, captured
--      whenever an employee is edited or its status is changed. Values are
--      stored as their human-readable display strings (department/
--      designation/state/city/programme names, not raw ids) so the log
--      reads directly without joining back to the master tables.
CREATE TABLE employee_update_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id  BIGINT NOT NULL REFERENCES employee(id) ON DELETE CASCADE,
    field_name   VARCHAR(50) NOT NULL,
    old_value    TEXT,
    new_value    TEXT,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by   VARCHAR(255),
    updated_by   VARCHAR(255)
);

CREATE INDEX idx_employee_update_log_employee_id ON employee_update_log(employee_id);
