-- V83: Employee Allocation — splits an employee's time across a Program and
--      a Project (both Programme rows: programme_id must reference a
--      type=Programme row, project_id must reference a type=Project row
--      whose own parent_programme_id equals programme_id — enforced in the
--      service layer, not by a DB constraint), with an optional
--      state/city deployment, an allocation percentage and dates.
CREATE TABLE employee_allocation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     BIGINT NOT NULL REFERENCES employee(id) ON DELETE CASCADE,
    programme_id    BIGINT NOT NULL REFERENCES programme(id),
    project_id      BIGINT NOT NULL REFERENCES programme(id),
    role            VARCHAR(255),
    allocation_pct  INTEGER NOT NULL CHECK (allocation_pct BETWEEN 1 AND 100),
    start_date      DATE,
    end_date        DATE,
    remark          TEXT,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255)
);

CREATE INDEX idx_employee_allocation_employee ON employee_allocation(employee_id);
CREATE INDEX idx_employee_allocation_programme ON employee_allocation(programme_id);
CREATE INDEX idx_employee_allocation_project ON employee_allocation(project_id);

CREATE TABLE employee_allocation_state (
    employee_allocation_id BIGINT NOT NULL REFERENCES employee_allocation(id) ON DELETE CASCADE,
    state_id                BIGINT NOT NULL REFERENCES state_master(id),
    PRIMARY KEY (employee_allocation_id, state_id)
);

CREATE TABLE employee_allocation_city (
    employee_allocation_id BIGINT NOT NULL REFERENCES employee_allocation(id) ON DELETE CASCADE,
    city_id                 BIGINT NOT NULL REFERENCES city_master(id),
    PRIMARY KEY (employee_allocation_id, city_id)
);
