-- V87: Payment Type Group master — chart-of-accounts group (e.g. Balance
--      Sheet, Income & Expenditure Heads) used to classify payment type
--      ledgers under Payment Type Master Configuration.
CREATE TABLE payment_type_group (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    status      BOOLEAN NOT NULL DEFAULT true,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255)
);

CREATE INDEX idx_payment_type_group_status ON payment_type_group(status);

INSERT INTO payment_type_group (name, status) VALUES
('Balance Sheet', true),
('Income & Expenditure Heads', true);
