-- V88: Payment Type Ledger master — ledger tied to a Payment Type Group,
--      selectable wherever a payment type classification is captured.
CREATE TABLE payment_type_ledger (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    group_id    BIGINT NOT NULL REFERENCES payment_type_group(id),
    status      BOOLEAN NOT NULL DEFAULT true,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255),
    CONSTRAINT uq_payment_type_ledger_name_group UNIQUE (name, group_id)
);

CREATE INDEX idx_payment_type_ledger_status ON payment_type_ledger(status);
CREATE INDEX idx_payment_type_ledger_group_id ON payment_type_ledger(group_id);

INSERT INTO payment_type_ledger (name, group_id, status)
SELECT v.name, g.id, v.status
FROM (VALUES
    ('Solar Infrastructure & Plant Equipment', 'Balance Sheet', true),
    ('Office IT & Hardware Assets', 'Balance Sheet', true),
    ('Staff Travel & Imprest Advances', 'Balance Sheet', true),
    ('Security Deposits & Prepayments', 'Balance Sheet', true),
    ('Vendor & Contractor Payables', 'Balance Sheet', true),
    ('TDS & Statutory Dues Payable', 'Balance Sheet', true),
    ('General Corpus Fund / Capital Reserve', 'Balance Sheet', true),
    ('Programme Implementation & Field Operations', 'Income & Expenditure Heads', true),
    ('Project Equipment Procurement & Material Supply', 'Income & Expenditure Heads', true),
    ('Direct Community Assistance & Subsidies', 'Income & Expenditure Heads', true),
    ('Administrative Overheads & Office Running', 'Income & Expenditure Heads', true),
    ('Professional Legal & Statutory Audit Fees', 'Income & Expenditure Heads', true),
    ('Grant Revenue & Institutional Contributions', 'Income & Expenditure Heads', true),
    ('Bank Interest & Investment Returns', 'Income & Expenditure Heads', true)
) AS v(name, group_name, status)
JOIN payment_type_group g ON g.name = v.group_name;
