-- V89: Finance transaction — a Debit (Out) or Credit (In) payment window
--      entry recorded through the "New Transaction" form. FK ids reference
--      donor_master, donor_fund_profile, grant_agreement (nullable),
--      payment_mode, payment_type_group and payment_type_ledger; party is a
--      free id/name pair since Payee has no backend master yet.
CREATE TABLE finance_transaction (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_code  VARCHAR(32) NOT NULL UNIQUE,
    type              VARCHAR(10) NOT NULL,
    book              VARCHAR(10) NOT NULL,
    transaction_date  DATE NOT NULL,
    category          VARCHAR(50) NOT NULL,
    party_id          VARCHAR(50) NOT NULL,
    party_name        VARCHAR(255) NOT NULL,
    donor_id          BIGINT NOT NULL REFERENCES donor_master(id),
    fund_profile_id   BIGINT NOT NULL REFERENCES donor_fund_profile(id),
    grant_id          BIGINT REFERENCES grant_agreement(id),
    amount            NUMERIC(18, 2) NOT NULL,
    bank_account      VARCHAR(50),
    payment_mode_id   BIGINT NOT NULL REFERENCES payment_mode(id),
    reference         VARCHAR(255),
    group_id          BIGINT NOT NULL REFERENCES payment_type_group(id),
    ledger_id         BIGINT NOT NULL REFERENCES payment_type_ledger(id),
    notes             TEXT,
    created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by        VARCHAR(255),
    updated_by        VARCHAR(255)
);

CREATE INDEX idx_finance_transaction_type ON finance_transaction(type);
CREATE INDEX idx_finance_transaction_donor_id ON finance_transaction(donor_id);
CREATE INDEX idx_finance_transaction_fund_profile_id ON finance_transaction(fund_profile_id);
CREATE INDEX idx_finance_transaction_date ON finance_transaction(transaction_date);
