-- V91: Donor Type master — manageable list of donor types (Corporate CSR,
--      Individual, Foundation, Government, …) surfaced under Master
--      Configuration, replacing the previously hardcoded DonorType enum.
--      `code` is the stable identifier existing donor rows already store in
--      donor_master.donor_type (e.g. 'CORPORATE') and business logic (CSR
--      donation rules) keys off; `name` is the display label shown on forms.
CREATE TABLE donor_type_master (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50) NOT NULL UNIQUE,
    name        VARCHAR(255) NOT NULL UNIQUE,
    status      BOOLEAN NOT NULL DEFAULT true,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  VARCHAR(255),
    updated_by  VARCHAR(255)
);

CREATE INDEX idx_donor_type_master_status ON donor_type_master(status);

INSERT INTO donor_type_master (code, name, status) VALUES
('CORPORATE', 'Corporate CSR', true),
('INDIVIDUAL', 'Individual', true),
('FOUNDATION', 'Foundation', true),
('GOVERNMENT', 'Government', true);
