import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { notificationApi } from '../api/notificationApi.js';

const listKey = (userId, unreadOnly) => ['notifications', 'list', String(userId), { unreadOnly }];
const countKey = (userId) => ['notifications', 'unreadCount', String(userId)];

/** Polls every two minutes: reminders are generated by a nightly job, not live. */
export function useNotifications(userId, { unreadOnly = false, limit = 50 } = {}) {
  return useQuery({
    queryKey: listKey(userId, unreadOnly),
    queryFn: () => notificationApi.list(userId, { unreadOnly, limit }),
    enabled: userId != null,
    refetchInterval: 120_000,
  });
}

export function useUnreadCount(userId) {
  return useQuery({
    queryKey: countKey(userId),
    queryFn: () => notificationApi.unreadCount(userId).then((d) => d.unread ?? 0),
    enabled: userId != null,
    refetchInterval: 120_000,
  });
}

export function useMarkNotificationRead() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: (id) => notificationApi.markRead(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['notifications'] }),
  });
}

export function useMarkAllNotificationsRead(userId) {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: () => notificationApi.markAllRead(userId),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ['notifications'] }),
  });
}
