export const donorRecords = [
  {
    donorId: "DNR-1001",
    donorCode: "TATA-RESTRICT-01",
    donorName: "Tata Foundation",
    donorSource: "Corporate Foundation",
    donorType: "Institutional",
    fundSourceDomicile: "Domestic",
    fcraApplicable: false,
    foreignFundSourceType: "-",
    foreignCountryName: "-",
    contactPerson: "Nitin Raina",
    email: "nitin.raina@tatafoundation.org",
    phone: "+91 98990 11223",
    address: "Bombay House, Mumbai, Maharashtra, India",
    panCardNumber: "AAACT1122R",
    bankAccountRef: "TATA-001-INR",
    active: true,
    createdAt: "2025-01-04T09:30:00.000Z",
    updatedAt: "2026-06-20T12:10:00.000Z",
    mouLink: "https://example.org/mou/tata-foundation",
    committedLakhs: 120,
    receivedLakhs: 80,
    fundType: "Restricted"
  },
  {
    donorId: "DNR-1002",
    donorCode: "GATES-FCRA-04",
    donorName: "Gates Foundation",
    donorSource: "Global Foundation",
    donorType: "Institutional",
    fundSourceDomicile: "Foreign",
    fcraApplicable: true,
    foreignFundSourceType: "Foundation Grant",
    foreignCountryName: "United States",
    contactPerson: "Nadia Brooks",
    email: "nadia.brooks@gatesfoundation.org",
    phone: "+1 206 709 3100",
    address: "500 5th Ave N, Seattle, Washington, USA",
    panCardNumber: "-",
    bankAccountRef: "FCRA-233-USD",
    active: true,
    createdAt: "2024-11-10T11:00:00.000Z",
    updatedAt: "2026-05-11T16:43:00.000Z",
    mouLink: "https://example.org/mou/gates-foundation",
    committedLakhs: 95,
    receivedLakhs: 65,
    fundType: "Restricted"
  },
  {
    donorId: "DNR-1003",
    donorCode: "AZIM-UNREST-02",
    donorName: "Azim Premji Phil.",
    donorSource: "Indian Philanthropy",
    donorType: "Institutional",
    fundSourceDomicile: "Domestic",
    fcraApplicable: false,
    foreignFundSourceType: "-",
    foreignCountryName: "-",
    contactPerson: "Ritu Sharma",
    email: "ritu.sharma@azimpremjiphilanthropy.in",
    phone: "+91 80444 12000",
    address: "Bengaluru, Karnataka, India",
    panCardNumber: "AACCA7821P",
    bankAccountRef: "AZIM-7821-INR",
    active: true,
    createdAt: "2025-02-18T08:25:00.000Z",
    updatedAt: "2026-06-01T10:01:00.000Z",
    mouLink: "https://example.org/mou/azim-premji",
    committedLakhs: 50,
    receivedLakhs: 50,
    fundType: "Unrestricted"
  },
  {
    donorId: "DNR-1004",
    donorCode: "ROCK-FCRA-09",
    donorName: "Rockefeller",
    donorSource: "Global Endowment",
    donorType: "Institutional",
    fundSourceDomicile: "Foreign",
    fcraApplicable: true,
    foreignFundSourceType: "Endowment Grant",
    foreignCountryName: "United States",
    contactPerson: "Sam Ellis",
    email: "sam.ellis@rockefeller.org",
    phone: "+1 212 852 8300",
    address: "420 5th Ave, New York, USA",
    panCardNumber: "-",
    bankAccountRef: "FCRA-488-USD",
    active: true,
    createdAt: "2025-03-11T10:15:00.000Z",
    updatedAt: "2026-06-23T06:42:00.000Z",
    mouLink: "https://example.org/mou/rockefeller",
    committedLakhs: 42,
    receivedLakhs: 21,
    fundType: "Restricted"
  },
  {
    donorId: "DNR-1005",
    donorCode: "IND-Pool-07",
    donorName: "Individual Giving Pool",
    donorSource: "Individuals",
    donorType: "Retail Cluster",
    fundSourceDomicile: "Domestic",
    fcraApplicable: false,
    foreignFundSourceType: "-",
    foreignCountryName: "-",
    contactPerson: "Devika Rao",
    email: "devika.rao@zariya.org",
    phone: "+91 99880 77889",
    address: "Bengaluru, Karnataka, India",
    panCardNumber: "AAATS2786D",
    bankAccountRef: "INDIV-POOL-INR",
    active: true,
    createdAt: "2024-08-21T07:15:00.000Z",
    updatedAt: "2026-06-29T15:06:00.000Z",
    mouLink: "https://example.org/mou/individual-pool",
    committedLakhs: 30,
    receivedLakhs: 18.5,
    fundType: "Unrestricted"
  },
  {
    donorId: "DNR-1006",
    donorCode: "BLMBRG-FCRA-11",
    donorName: "Bloomberg Philanthropies",
    donorSource: "Global Foundation",
    donorType: "Institutional",
    fundSourceDomicile: "Foreign",
    fcraApplicable: true,
    foreignFundSourceType: "Program Grant",
    foreignCountryName: "United States",
    contactPerson: "Aisha Rahman",
    email: "aisha.rahman@bloomberg.org",
    phone: "+1 212 205 0100",
    address: "25 East 78th Street, New York, USA",
    panCardNumber: "-",
    bankAccountRef: "FCRA-611-USD",
    active: true,
    createdAt: "2025-04-13T09:00:00.000Z",
    updatedAt: "2026-06-30T05:55:00.000Z",
    mouLink: "https://example.org/mou/bloomberg-philanthropies",
    committedLakhs: 28,
    receivedLakhs: 8,
    fundType: "Restricted"
  }
];

export const detailFieldSchema = [
  { key: "donorId", label: "Donor ID" },
  { key: "donorCode", label: "Donor Code" },
  { key: "donorName", label: "Donor Name" },
  { key: "donorSource", label: "Donor Source" },
  { key: "donorType", label: "Donor Type" },
  { key: "fundSourceDomicile", label: "Fund Source (Domicile)" },
  { key: "fcraApplicable", label: "FCRA Applicable", type: "boolean" },
  { key: "foreignFundSourceType", label: "Foreign Fund Source Type" },
  { key: "foreignCountryName", label: "Foreign Country Name" },
  { key: "contactPerson", label: "Contact Person" },
  { key: "email", label: "Email", type: "email" },
  { key: "phone", label: "Phone" },
  { key: "address", label: "Address" },
  { key: "panCardNumber", label: "Pan Card Number" },
  { key: "bankAccountRef", label: "Bank Account Ref *" },
  { key: "active", label: "Active", type: "boolean" },
  { key: "createdAt", label: "Created At", type: "datetime" },
  { key: "updatedAt", label: "Updated At", type: "datetime" },
  { key: "mouLink", label: "MoU (Link)", type: "link" }
];
